-- ============================================================================
-- DISTRIBUTED PRICE INGESTION - CRON JOB SETUP
-- ============================================================================
-- Purpose: Create 52 staggered batch jobs for 1,043-asset price updates
-- Architecture: 20 assets/batch × 52 batches = 1,040 assets (covers all 1,043)
-- Timing: Each batch runs every 30s, staggered by 1s intervals
-- Result: Full universe refresh in ~26 seconds, repeats every 30s
-- Maximum staleness: 30 seconds (down from hours)
-- ============================================================================

-- Step 1: Delete old monolithic cron jobs
SELECT cron.unschedule('15min-prices-yahoo');
SELECT cron.unschedule('2min-prices-ingest');

-- Step 2: Create 52 staggered batch cron jobs
-- Pattern: Each batch at :Xs and :(X+30)s every minute
-- Batch 0: :00 and :30  | Batch 1: :01 and :31 | ... | Batch 25: :25 and :55

SELECT cron.schedule('prices-batch-00', '0,30 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 0}'::jsonb);$$);
SELECT cron.schedule('prices-batch-01', '1,31 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 1}'::jsonb);$$);
SELECT cron.schedule('prices-batch-02', '2,32 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 2}'::jsonb);$$);
SELECT cron.schedule('prices-batch-03', '3,33 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 3}'::jsonb);$$);
SELECT cron.schedule('prices-batch-04', '4,34 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 4}'::jsonb);$$);
SELECT cron.schedule('prices-batch-05', '5,35 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 5}'::jsonb);$$);
SELECT cron.schedule('prices-batch-06', '6,36 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 6}'::jsonb);$$);
SELECT cron.schedule('prices-batch-07', '7,37 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 7}'::jsonb);$$);
SELECT cron.schedule('prices-batch-08', '8,38 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 8}'::jsonb);$$);
SELECT cron.schedule('prices-batch-09', '9,39 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 9}'::jsonb);$$);
SELECT cron.schedule('prices-batch-10', '10,40 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 10}'::jsonb);$$);
SELECT cron.schedule('prices-batch-11', '11,41 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 11}'::jsonb);$$);
SELECT cron.schedule('prices-batch-12', '12,42 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 12}'::jsonb);$$);
SELECT cron.schedule('prices-batch-13', '13,43 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 13}'::jsonb);$$);
SELECT cron.schedule('prices-batch-14', '14,44 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 14}'::jsonb);$$);
SELECT cron.schedule('prices-batch-15', '15,45 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 15}'::jsonb);$$);
SELECT cron.schedule('prices-batch-16', '16,46 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 16}'::jsonb);$$);
SELECT cron.schedule('prices-batch-17', '17,47 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 17}'::jsonb);$$);
SELECT cron.schedule('prices-batch-18', '18,48 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 18}'::jsonb);$$);
SELECT cron.schedule('prices-batch-19', '19,49 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 19}'::jsonb);$$);
SELECT cron.schedule('prices-batch-20', '20,50 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 20}'::jsonb);$$);
SELECT cron.schedule('prices-batch-21', '21,51 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 21}'::jsonb);$$);
SELECT cron.schedule('prices-batch-22', '22,52 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 22}'::jsonb);$$);
SELECT cron.schedule('prices-batch-23', '23,53 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 23}'::jsonb);$$);
SELECT cron.schedule('prices-batch-24', '24,54 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 24}'::jsonb);$$);
SELECT cron.schedule('prices-batch-25', '25,55 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 25}'::jsonb);$$);
SELECT cron.schedule('prices-batch-26', '26,56 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 26}'::jsonb);$$);
SELECT cron.schedule('prices-batch-27', '27,57 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 27}'::jsonb);$$);
SELECT cron.schedule('prices-batch-28', '28,58 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 28}'::jsonb);$$);
SELECT cron.schedule('prices-batch-29', '29,59 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 29}'::jsonb);$$);
SELECT cron.schedule('prices-batch-30', '0,30 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 30}'::jsonb);$$);
SELECT cron.schedule('prices-batch-31', '1,31 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 31}'::jsonb);$$);
SELECT cron.schedule('prices-batch-32', '2,32 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 32}'::jsonb);$$);
SELECT cron.schedule('prices-batch-33', '3,33 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 33}'::jsonb);$$);
SELECT cron.schedule('prices-batch-34', '4,34 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 34}'::jsonb);$$);
SELECT cron.schedule('prices-batch-35', '5,35 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 35}'::jsonb);$$);
SELECT cron.schedule('prices-batch-36', '6,36 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 36}'::jsonb);$$);
SELECT cron.schedule('prices-batch-37', '7,37 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 37}'::jsonb);$$);
SELECT cron.schedule('prices-batch-38', '8,38 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 38}'::jsonb);$$);
SELECT cron.schedule('prices-batch-39', '9,39 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 39}'::jsonb);$$);
SELECT cron.schedule('prices-batch-40', '10,40 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 40}'::jsonb);$$);
SELECT cron.schedule('prices-batch-41', '11,41 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 41}'::jsonb);$$);
SELECT cron.schedule('prices-batch-42', '12,42 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 42}'::jsonb);$$);
SELECT cron.schedule('prices-batch-43', '13,43 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 43}'::jsonb);$$);
SELECT cron.schedule('prices-batch-44', '14,44 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 44}'::jsonb);$$);
SELECT cron.schedule('prices-batch-45', '15,45 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 45}'::jsonb);$$);
SELECT cron.schedule('prices-batch-46', '16,46 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 46}'::jsonb);$$);
SELECT cron.schedule('prices-batch-47', '17,47 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 47}'::jsonb);$$);
SELECT cron.schedule('prices-batch-48', '18,48 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 48}'::jsonb);$$);
SELECT cron.schedule('prices-batch-49', '19,49 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 49}'::jsonb);$$);
SELECT cron.schedule('prices-batch-50', '20,50 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 50}'::jsonb);$$);
SELECT cron.schedule('prices-batch-51', '21,51 * * * * *', $$SELECT net.http_post(url:='https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers:='{"Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.HwW5eYCqvAUKgb7_3oUpSPFWm0KQo83vKGAYB-YPpLE"}'::jsonb, body:='{"batch_id": 51}'::jsonb);$$);

-- Step 3: Verify cron jobs created
SELECT jobname, schedule FROM cron.job WHERE jobname LIKE 'prices-batch-%' ORDER BY jobname;
