// Top 200 Cryptocurrencies by market cap with major trading pairs
export const CRYPTO_ASSETS = [
  // Top 20 with USD and EUR pairs
  { ticker: 'BTC/USD', name: 'Bitcoin / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'BTC/EUR', name: 'Bitcoin / Euro', exchange: 'CRYPTO' },
  { ticker: 'BTC/USDT', name: 'Bitcoin / Tether', exchange: 'CRYPTO' },
  { ticker: 'ETH/USD', name: 'Ethereum / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'ETH/EUR', name: 'Ethereum / Euro', exchange: 'CRYPTO' },
  { ticker: 'ETH/USDT', name: 'Ethereum / Tether', exchange: 'CRYPTO' },
  { ticker: 'ETH/BTC', name: 'Ethereum / Bitcoin', exchange: 'CRYPTO' },
  { ticker: 'BNB/USD', name: 'Binance Coin / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'BNB/USDT', name: 'Binance Coin / Tether', exchange: 'CRYPTO' },
  { ticker: 'XRP/USD', name: 'Ripple / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'XRP/EUR', name: 'Ripple / Euro', exchange: 'CRYPTO' },
  { ticker: 'XRP/USDT', name: 'Ripple / Tether', exchange: 'CRYPTO' },
  { ticker: 'SOL/USD', name: 'Solana / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'SOL/USDT', name: 'Solana / Tether', exchange: 'CRYPTO' },
  { ticker: 'ADA/USD', name: 'Cardano / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'ADA/USDT', name: 'Cardano / Tether', exchange: 'CRYPTO' },
  { ticker: 'DOGE/USD', name: 'Dogecoin / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'DOGE/USDT', name: 'Dogecoin / Tether', exchange: 'CRYPTO' },
  { ticker: 'TRX/USD', name: 'TRON / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'TRX/USDT', name: 'TRON / Tether', exchange: 'CRYPTO' },
  { ticker: 'AVAX/USD', name: 'Avalanche / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'AVAX/USDT', name: 'Avalanche / Tether', exchange: 'CRYPTO' },
  { ticker: 'DOT/USD', name: 'Polkadot / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'DOT/USDT', name: 'Polkadot / Tether', exchange: 'CRYPTO' },
  { ticker: 'MATIC/USD', name: 'Polygon / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'MATIC/USDT', name: 'Polygon / Tether', exchange: 'CRYPTO' },
  { ticker: 'LTC/USD', name: 'Litecoin / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'LTC/USDT', name: 'Litecoin / Tether', exchange: 'CRYPTO' },
  { ticker: 'LINK/USD', name: 'Chainlink / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'LINK/USDT', name: 'Chainlink / Tether', exchange: 'CRYPTO' },
  { ticker: 'UNI/USD', name: 'Uniswap / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'UNI/USDT', name: 'Uniswap / Tether', exchange: 'CRYPTO' },
  { ticker: 'ATOM/USD', name: 'Cosmos / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'ATOM/USDT', name: 'Cosmos / Tether', exchange: 'CRYPTO' },
  { ticker: 'XLM/USD', name: 'Stellar / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'XLM/USDT', name: 'Stellar / Tether', exchange: 'CRYPTO' },
  { ticker: 'ALGO/USD', name: 'Algorand / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'ALGO/USDT', name: 'Algorand / Tether', exchange: 'CRYPTO' },
  { ticker: 'VET/USD', name: 'VeChain / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'VET/USDT', name: 'VeChain / Tether', exchange: 'CRYPTO' },
  
  // DeFi tokens (20-50)
  { ticker: 'AAVE/USD', name: 'Aave / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'AAVE/USDT', name: 'Aave / Tether', exchange: 'CRYPTO' },
  { ticker: 'MKR/USD', name: 'Maker / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'MKR/USDT', name: 'Maker / Tether', exchange: 'CRYPTO' },
  { ticker: 'CRV/USD', name: 'Curve DAO Token / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'CRV/USDT', name: 'Curve DAO Token / Tether', exchange: 'CRYPTO' },
  { ticker: 'LDO/USD', name: 'Lido DAO / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'LDO/USDT', name: 'Lido DAO / Tether', exchange: 'CRYPTO' },
  { ticker: 'SNX/USD', name: 'Synthetix / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'SNX/USDT', name: 'Synthetix / Tether', exchange: 'CRYPTO' },
  // COMP/USD removed - not supported by Twelve Data
  { ticker: 'SUSHI/USD', name: 'SushiSwap / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'SUSHI/USDT', name: 'SushiSwap / Tether', exchange: 'CRYPTO' },
  // YFI removed - not supported by Twelve Data
  { ticker: '1INCH/USD', name: '1inch / US Dollar', exchange: 'CRYPTO' },
  { ticker: '1INCH/USDT', name: '1inch / Tether', exchange: 'CRYPTO' },
  { ticker: 'BAL/USD', name: 'Balancer / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'BAL/USDT', name: 'Balancer / Tether', exchange: 'CRYPTO' },
  
  // Layer 2 & Scaling (50-70)
  { ticker: 'FIL/USD', name: 'Filecoin / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'FIL/USDT', name: 'Filecoin / Tether', exchange: 'CRYPTO' },
  { ticker: 'NEAR/USD', name: 'NEAR Protocol / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'NEAR/USDT', name: 'NEAR Protocol / Tether', exchange: 'CRYPTO' },
  { ticker: 'APT/USD', name: 'Aptos / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'APT/USDT', name: 'Aptos / Tether', exchange: 'CRYPTO' },
  { ticker: 'OP/USD', name: 'Optimism / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'OP/USDT', name: 'Optimism / Tether', exchange: 'CRYPTO' },
  { ticker: 'ARB/USD', name: 'Arbitrum / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'ARB/USDT', name: 'Arbitrum / Tether', exchange: 'CRYPTO' },
  { ticker: 'IMX/USD', name: 'Immutable X / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'IMX/USDT', name: 'Immutable X / Tether', exchange: 'CRYPTO' },
  { ticker: 'STRK/USD', name: 'StarkNet / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'STRK/USDT', name: 'StarkNet / Tether', exchange: 'CRYPTO' },
  
  // Metaverse & Gaming (70-90)
  { ticker: 'SAND/USD', name: 'The Sandbox / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'SAND/USDT', name: 'The Sandbox / Tether', exchange: 'CRYPTO' },
  { ticker: 'MANA/USD', name: 'Decentraland / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'MANA/USDT', name: 'Decentraland / Tether', exchange: 'CRYPTO' },
  { ticker: 'AXS/USD', name: 'Axie Infinity / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'AXS/USDT', name: 'Axie Infinity / Tether', exchange: 'CRYPTO' },
  { ticker: 'GALA/USD', name: 'Gala / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'GALA/USDT', name: 'Gala / Tether', exchange: 'CRYPTO' },
  { ticker: 'APE/USD', name: 'ApeCoin / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'APE/USDT', name: 'ApeCoin / Tether', exchange: 'CRYPTO' },
  { ticker: 'ENJ/USD', name: 'Enjin Coin / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'ENJ/USDT', name: 'Enjin Coin / Tether', exchange: 'CRYPTO' },
  { ticker: 'THETA/USD', name: 'Theta Network / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'THETA/USDT', name: 'Theta Network / Tether', exchange: 'CRYPTO' },
  
  // Meme coins & Community (90-110)
  { ticker: 'SHIB/USD', name: 'Shiba Inu / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'SHIB/USDT', name: 'Shiba Inu / Tether', exchange: 'CRYPTO' },
  // PEPE removed - not supported by Twelve Data
  { ticker: 'FLOKI/USD', name: 'Floki Inu / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'FLOKI/USDT', name: 'Floki Inu / Tether', exchange: 'CRYPTO' },
  
  // Utility & Platform tokens (110-150)
  { ticker: 'BAT/USD', name: 'Basic Attention Token / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'BAT/USDT', name: 'Basic Attention Token / Tether', exchange: 'CRYPTO' },
  // ZRX removed - not supported by Twelve Data
  { ticker: 'RUNE/USD', name: 'THORChain / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'RUNE/USDT', name: 'THORChain / Tether', exchange: 'CRYPTO' },
  { ticker: 'FTM/USD', name: 'Fantom / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'FTM/USDT', name: 'Fantom / Tether', exchange: 'CRYPTO' },
  { ticker: 'ONE/USD', name: 'Harmony / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'ONE/USDT', name: 'Harmony / Tether', exchange: 'CRYPTO' },
  // ZIL removed - not supported by Twelve Data
  { ticker: 'ICX/USD', name: 'ICON / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'ICX/USDT', name: 'ICON / Tether', exchange: 'CRYPTO' },
  // WAVES removed - not supported by Twelve Data
  { ticker: 'KAVA/USD', name: 'Kava / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'KAVA/USDT', name: 'Kava / Tether', exchange: 'CRYPTO' },
  { ticker: 'CELO/USD', name: 'Celo / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'CELO/USDT', name: 'Celo / Tether', exchange: 'CRYPTO' },
  { ticker: 'ROSE/USD', name: 'Oasis Network / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'ROSE/USDT', name: 'Oasis Network / Tether', exchange: 'CRYPTO' },
  { ticker: 'EGLD/USD', name: 'MultiversX / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'EGLD/USDT', name: 'MultiversX / Tether', exchange: 'CRYPTO' },
  { ticker: 'HBAR/USD', name: 'Hedera / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'HBAR/USDT', name: 'Hedera / Tether', exchange: 'CRYPTO' },
  { ticker: 'FLOW/USD', name: 'Flow / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'FLOW/USDT', name: 'Flow / Tether', exchange: 'CRYPTO' },
  { ticker: 'ICP/USD', name: 'Internet Computer / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'ICP/USDT', name: 'Internet Computer / Tether', exchange: 'CRYPTO' },
  { ticker: 'MINA/USD', name: 'Mina Protocol / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'MINA/USDT', name: 'Mina Protocol / Tether', exchange: 'CRYPTO' },
  // GRT removed - not supported by Twelve Data
  { ticker: 'FET/USD', name: 'Fetch.ai / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'FET/USDT', name: 'Fetch.ai / Tether', exchange: 'CRYPTO' },
  { ticker: 'AGIX/USD', name: 'SingularityNET / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'AGIX/USDT', name: 'SingularityNET / Tether', exchange: 'CRYPTO' },
  { ticker: 'OCEAN/USD', name: 'Ocean Protocol / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'OCEAN/USDT', name: 'Ocean Protocol / Tether', exchange: 'CRYPTO' },
  { ticker: 'REN/USD', name: 'Ren / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'REN/USDT', name: 'Ren / Tether', exchange: 'CRYPTO' },
  { ticker: 'BAND/USD', name: 'Band Protocol / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'BAND/USDT', name: 'Band Protocol / Tether', exchange: 'CRYPTO' },
  { ticker: 'ANKR/USD', name: 'Ankr / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'ANKR/USDT', name: 'Ankr / Tether', exchange: 'CRYPTO' },
  { ticker: 'STORJ/USD', name: 'Storj / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'STORJ/USDT', name: 'Storj / Tether', exchange: 'CRYPTO' },
  { ticker: 'SKL/USD', name: 'SKALE Network / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'SKL/USDT', name: 'SKALE Network / Tether', exchange: 'CRYPTO' },
  { ticker: 'CKB/USD', name: 'Nervos Network / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'CKB/USDT', name: 'Nervos Network / Tether', exchange: 'CRYPTO' },
  
  // Privacy coins - XMR, ZEC, DASH removed (not supported by Twelve Data)
  { ticker: 'DCR/USD', name: 'Decred / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'DCR/USDT', name: 'Decred / Tether', exchange: 'CRYPTO' },
  
  // Stablecoins for reference
  { ticker: 'USDT/USD', name: 'Tether / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'USDC/USD', name: 'USD Coin / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'DAI/USD', name: 'Dai / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'BUSD/USD', name: 'Binance USD / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'TUSD/USD', name: 'TrueUSD / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'USDP/USD', name: 'Pax Dollar / US Dollar', exchange: 'CRYPTO' },
  { ticker: 'FRAX/USD', name: 'Frax / US Dollar', exchange: 'CRYPTO' },
  
  // Cross pairs (180-200)
  { ticker: 'LINK/ETH', name: 'Chainlink / Ethereum', exchange: 'CRYPTO' },
  { ticker: 'UNI/ETH', name: 'Uniswap / Ethereum', exchange: 'CRYPTO' },
  { ticker: 'AAVE/ETH', name: 'Aave / Ethereum', exchange: 'CRYPTO' },
  { ticker: 'MATIC/ETH', name: 'Polygon / Ethereum', exchange: 'CRYPTO' },
  { ticker: 'SOL/ETH', name: 'Solana / Ethereum', exchange: 'CRYPTO' },
  { ticker: 'AVAX/ETH', name: 'Avalanche / Ethereum', exchange: 'CRYPTO' },
  { ticker: 'DOT/BTC', name: 'Polkadot / Bitcoin', exchange: 'CRYPTO' },
  { ticker: 'ADA/BTC', name: 'Cardano / Bitcoin', exchange: 'CRYPTO' },
  { ticker: 'XRP/BTC', name: 'Ripple / Bitcoin', exchange: 'CRYPTO' },
  { ticker: 'LTC/BTC', name: 'Litecoin / Bitcoin', exchange: 'CRYPTO' },
];
