// Russell 2000 Top 200 Small Cap Growth Leaders
export const RUSSELL_2000 = [
  { ticker: 'RXRX', name: 'Recursion Pharmaceuticals Inc.', exchange: 'NASDAQ' },
  { ticker: 'BROS', name: 'Dutch Bros Inc.', exchange: 'NYSE' },
  { ticker: 'CELH', name: 'Celsius Holdings Inc.', exchange: 'NASDAQ' },
  { ticker: 'SMCI', name: 'Super Micro Computer Inc.', exchange: 'NASDAQ' },
  { ticker: 'IONQ', name: 'IonQ Inc.', exchange: 'NYSE' },
  { ticker: 'CVNA', name: 'Carvana Co.', exchange: 'NYSE' },
  { ticker: 'TOST', name: 'Toast Inc.', exchange: 'NYSE' },
  { ticker: 'FOUR', name: 'Shift4 Payments Inc.', exchange: 'NYSE' },
  { ticker: 'SAIA', name: 'Saia Inc.', exchange: 'NASDAQ' },
  { ticker: 'WOLF', name: 'Wolfspeed Inc.', exchange: 'NYSE' },
  { ticker: 'VERX', name: 'Vertex Inc.', exchange: 'NASDAQ' },
  { ticker: 'BRBR', name: 'BellRing Brands Inc.', exchange: 'NYSE' },
  { ticker: 'QTWO', name: 'Q2 Holdings Inc.', exchange: 'NYSE' },
  { ticker: 'STEP', name: 'StepStone Group Inc.', exchange: 'NASDAQ' },
  { ticker: 'RH', name: 'RH (Restoration Hardware)', exchange: 'NYSE' },
  { ticker: 'AFRM', name: 'Affirm Holdings Inc.', exchange: 'NASDAQ' },
  { ticker: 'SOFI', name: 'SoFi Technologies Inc.', exchange: 'NASDAQ' },
  { ticker: 'UPST', name: 'Upstart Holdings Inc.', exchange: 'NASDAQ' },
  { ticker: 'LPLA', name: 'LPL Financial Holdings Inc.', exchange: 'NASDAQ' },
  { ticker: 'RBLX', name: 'Roblox Corporation', exchange: 'NYSE' },
  { ticker: 'U', name: 'Unity Software Inc.', exchange: 'NYSE' },
  { ticker: 'RIVN', name: 'Rivian Automotive Inc.', exchange: 'NASDAQ' },
  { ticker: 'LCID', name: 'Lucid Group Inc.', exchange: 'NASDAQ' },
  { ticker: 'XPEV', name: 'XPeng Inc.', exchange: 'NYSE' },
  { ticker: 'NIO', name: 'NIO Inc.', exchange: 'NYSE' },
  { ticker: 'LI', name: 'Li Auto Inc.', exchange: 'NASDAQ' },
  { ticker: 'PLUG', name: 'Plug Power Inc.', exchange: 'NASDAQ' },
  { ticker: 'FCEL', name: 'FuelCell Energy Inc.', exchange: 'NASDAQ' },
  { ticker: 'BLDP', name: 'Ballard Power Systems Inc.', exchange: 'NASDAQ' },
  { ticker: 'BE', name: 'Bloom Energy Corporation', exchange: 'NYSE' },
  { ticker: 'RUN', name: 'Sunrun Inc.', exchange: 'NASDAQ' },
  { ticker: 'NOVA', name: 'Sunnova Energy International Inc.', exchange: 'NYSE' },
  { ticker: 'ARRY', name: 'Array Technologies Inc.', exchange: 'NASDAQ' },
  { ticker: 'MAXN', name: 'Maxeon Solar Technologies Ltd.', exchange: 'NASDAQ' },
  { ticker: 'SHLS', name: 'Shoals Technologies Group Inc.', exchange: 'NASDAQ' },
  { ticker: 'VKTX', name: 'Viking Therapeutics Inc.', exchange: 'NASDAQ' },
  { ticker: 'SRRK', name: 'Scholar Rock Holding Corporation', exchange: 'NASDAQ' },
  { ticker: 'PRVA', name: 'Privia Health Group Inc.', exchange: 'NASDAQ' },
  { ticker: 'ACHR', name: 'Archer Aviation Inc.', exchange: 'NYSE' },
  { ticker: 'JOBY', name: 'Joby Aviation Inc.', exchange: 'NYSE' },
  { ticker: 'LILM', name: 'Lilium N.V.', exchange: 'NASDAQ' },
  { ticker: 'EVTL', name: 'Vertical Aerospace Ltd.', exchange: 'NYSE' },
  { ticker: 'BLDE', name: 'Blade Air Mobility Inc.', exchange: 'NASDAQ' },
  { ticker: 'BOWX', name: 'BowX Acquisition Corp.', exchange: 'NASDAQ' },
  { ticker: 'SPCE', name: 'Virgin Galactic Holdings Inc.', exchange: 'NYSE' },
  { ticker: 'RKLB', name: 'Rocket Lab USA Inc.', exchange: 'NASDAQ' },
  { ticker: 'ASTS', name: 'AST SpaceMobile Inc.', exchange: 'NASDAQ' },
  { ticker: 'LUNR', name: 'Intuitive Machines Inc.', exchange: 'NASDAQ' },
  { ticker: 'VORB', name: 'Virgin Orbit Holdings Inc.', exchange: 'NASDAQ' },
  { ticker: 'SATS', name: 'EchoStar Corporation', exchange: 'NASDAQ' },
  { ticker: 'GILT', name: 'Gilat Satellite Networks Ltd.', exchange: 'NASDAQ' },
  { ticker: 'VSAT', name: 'Viasat Inc.', exchange: 'NASDAQ' },
  { ticker: 'GSAT', name: 'Globalstar Inc.', exchange: 'NYSE' },
  { ticker: 'IRDM', name: 'Iridium Communications Inc.', exchange: 'NASDAQ' },
  { ticker: 'OKLO', name: 'Oklo Inc.', exchange: 'NYSE' },
  { ticker: 'SMR', name: 'NuScale Power Corporation', exchange: 'NYSE' },
  { ticker: 'LEU', name: 'Centrus Energy Corp.', exchange: 'NYSE' },
  { ticker: 'UUUU', name: 'Energy Fuels Inc.', exchange: 'NYSE' },
  { ticker: 'UEC', name: 'Uranium Energy Corp.', exchange: 'NYSE' },
  { ticker: 'CCJ', name: 'Cameco Corporation', exchange: 'NYSE' },
  { ticker: 'DNN', name: 'Denison Mines Corp.', exchange: 'NYSE' },
  { ticker: 'NXE', name: 'NexGen Energy Ltd.', exchange: 'NYSE' },
  { ticker: 'BWEN', name: 'Broadwind Inc.', exchange: 'NASDAQ' },
  { ticker: 'CLNE', name: 'Clean Energy Fuels Corp.', exchange: 'NASDAQ' },
  { ticker: 'CHPT', name: 'ChargePoint Holdings Inc.', exchange: 'NYSE' },
  { ticker: 'EVGO', name: 'EVgo Inc.', exchange: 'NASDAQ' },
  { ticker: 'BLNK', name: 'Blink Charging Co.', exchange: 'NASDAQ' },
  { ticker: 'VLTA', name: 'Volta Inc.', exchange: 'NYSE' },
  { ticker: 'QS', name: 'QuantumScape Corporation', exchange: 'NYSE' },
  { ticker: 'SES', name: 'SES AI Corporation', exchange: 'NYSE' },
  { ticker: 'SLDP', name: 'Solid Power Inc.', exchange: 'NASDAQ' },
  { ticker: 'ENVX', name: 'Enovix Corporation', exchange: 'NASDAQ' },
  { ticker: 'FREYR', name: 'FREYR Battery', exchange: 'NYSE' },
  { ticker: 'CBAT', name: 'CBAK Energy Technology Inc.', exchange: 'NASDAQ' },
  { ticker: 'LAC', name: 'Lithium Americas Corp.', exchange: 'NYSE' },
  { ticker: 'LTHM', name: 'Livent Corporation', exchange: 'NYSE' },
  { ticker: 'SQM', name: 'Sociedad Quimica y Minera de Chile S.A.', exchange: 'NYSE' },
  { ticker: 'PLL', name: 'Piedmont Lithium Inc.', exchange: 'NASDAQ' },
  { ticker: 'MP', name: 'MP Materials Corp.', exchange: 'NYSE' },
  { ticker: 'LITM', name: 'Snow Lake Resources Ltd.', exchange: 'NASDAQ' },
  { ticker: 'IONR', name: 'ioneer Ltd.', exchange: 'NASDAQ' },
  { ticker: 'RGTI', name: 'Rigetti Computing Inc.', exchange: 'NASDAQ' },
  { ticker: 'QUBT', name: 'Quantum Computing Inc.', exchange: 'NASDAQ' },
  { ticker: 'QBTS', name: 'D-Wave Quantum Inc.', exchange: 'NYSE' },
  { ticker: 'ARQQ', name: 'Arqit Quantum Inc.', exchange: 'NASDAQ' },
  { ticker: 'QMCO', name: 'Quantum Corporation', exchange: 'NASDAQ' },
  { ticker: 'AI', name: 'C3.ai Inc.', exchange: 'NYSE' },
  { ticker: 'BBAI', name: 'BigBear.ai Holdings Inc.', exchange: 'NYSE' },
  { ticker: 'SOUN', name: 'SoundHound AI Inc.', exchange: 'NASDAQ' },
  { ticker: 'PATH', name: 'UiPath Inc.', exchange: 'NYSE' },
  { ticker: 'AMBA', name: 'Ambarella Inc.', exchange: 'NASDAQ' },
  { ticker: 'GENI', name: 'Genius Sports Limited', exchange: 'NYSE' },
  { ticker: 'FUBO', name: 'fuboTV Inc.', exchange: 'NYSE' },
  { ticker: 'DKNG', name: 'DraftKings Inc.', exchange: 'NASDAQ' },
  { ticker: 'PENN', name: 'PENN Entertainment Inc.', exchange: 'NASDAQ' },
  { ticker: 'RSI', name: 'Rush Street Interactive Inc.', exchange: 'NYSE' },
  { ticker: 'CHDN', name: 'Churchill Downs Inc.', exchange: 'NASDAQ' },
  { ticker: 'FLYW', name: 'Flywire Corporation', exchange: 'NASDAQ' },
  { ticker: 'BILL', name: 'Bill.com Holdings Inc.', exchange: 'NYSE' },
  { ticker: 'SPOT', name: 'Spotify Technology S.A.', exchange: 'NYSE' },
  { ticker: 'HOOD', name: 'Robinhood Markets Inc.', exchange: 'NASDAQ' },
  { ticker: 'COIN', name: 'Coinbase Global Inc.', exchange: 'NASDAQ' },
  { ticker: 'SHOP', name: 'Shopify Inc.', exchange: 'NYSE' },
  { ticker: 'DASH', name: 'DoorDash Inc.', exchange: 'NYSE' },
  { ticker: 'ABNB', name: 'Airbnb Inc.', exchange: 'NASDAQ' },
  { ticker: 'UBER', name: 'Uber Technologies Inc.', exchange: 'NYSE' },
  { ticker: 'LYFT', name: 'Lyft Inc.', exchange: 'NASDAQ' },
  { ticker: 'DUOL', name: 'Duolingo Inc.', exchange: 'NASDAQ' },
  { ticker: 'GDDY', name: 'GoDaddy Inc.', exchange: 'NYSE' },
  { ticker: 'ZM', name: 'Zoom Video Communications Inc.', exchange: 'NASDAQ' },
  { ticker: 'DOCU', name: 'DocuSign Inc.', exchange: 'NASDAQ' },
  { ticker: 'TWLO', name: 'Twilio Inc.', exchange: 'NYSE' },
  { ticker: 'NET', name: 'Cloudflare Inc.', exchange: 'NYSE' },
  { ticker: 'DDOG', name: 'Datadog Inc.', exchange: 'NASDAQ' },
  { ticker: 'SNOW', name: 'Snowflake Inc.', exchange: 'NYSE' },
  { ticker: 'CRWD', name: 'CrowdStrike Holdings Inc.', exchange: 'NASDAQ' },
  { ticker: 'ZS', name: 'Zscaler Inc.', exchange: 'NASDAQ' },
  { ticker: 'OKTA', name: 'Okta Inc.', exchange: 'NASDAQ' },
  { ticker: 'COUP', name: 'Coupa Software Incorporated', exchange: 'NASDAQ' },
  { ticker: 'VEEV', name: 'Veeva Systems Inc.', exchange: 'NYSE' },
  { ticker: 'WDAY', name: 'Workday Inc.', exchange: 'NASDAQ' },
  { ticker: 'ZI', name: 'ZoomInfo Technologies Inc.', exchange: 'NASDAQ' },
  { ticker: 'HCP', name: 'HashiCorp Inc.', exchange: 'NASDAQ' },
  { ticker: 'MDB', name: 'MongoDB Inc.', exchange: 'NASDAQ' },
  { ticker: 'CFLT', name: 'Confluent Inc.', exchange: 'NASDAQ' },
  { ticker: 'PCOR', name: 'Procore Technologies Inc.', exchange: 'NYSE' },
  { ticker: 'GTLB', name: 'GitLab Inc.', exchange: 'NASDAQ' },
  { ticker: 'S', name: 'SentinelOne Inc.', exchange: 'NYSE' },
  { ticker: 'JAMF', name: 'Jamf Holding Corp.', exchange: 'NASDAQ' },
  { ticker: 'NCNO', name: 'nCino Inc.', exchange: 'NASDAQ' },
  { ticker: 'PSTG', name: 'Pure Storage Inc.', exchange: 'NYSE' },
  { ticker: 'WIX', name: 'Wix.com Ltd.', exchange: 'NASDAQ' },
  { ticker: 'MNDY', name: 'monday.com Ltd.', exchange: 'NASDAQ' },
  { ticker: 'FROG', name: 'JFrog Ltd.', exchange: 'NASDAQ' },
  { ticker: 'BRZE', name: 'Braze Inc.', exchange: 'NASDAQ' },
  { ticker: 'PD', name: 'PagerDuty Inc.', exchange: 'NYSE' },
  { ticker: 'ESTC', name: 'Elastic N.V.', exchange: 'NYSE' },
  { ticker: 'DOCN', name: 'DigitalOcean Holdings Inc.', exchange: 'NYSE' },
  { ticker: 'APPN', name: 'Appian Corporation', exchange: 'NASDAQ' },
  { ticker: 'PLTR', name: 'Palantir Technologies Inc.', exchange: 'NYSE' },
  { ticker: 'RDFN', name: 'Redfin Corporation', exchange: 'NASDAQ' },
  { ticker: 'OPEN', name: 'Opendoor Technologies Inc.', exchange: 'NASDAQ' },
  { ticker: 'RKT', name: 'Rocket Companies Inc.', exchange: 'NYSE' },
  { ticker: 'COMP', name: 'Compass Inc.', exchange: 'NYSE' },
  { ticker: 'PENN', name: 'PENN Entertainment Inc.', exchange: 'NASDAQ' },
  { ticker: 'BALY', name: 'Bally\'s Corporation', exchange: 'NYSE' },
  { ticker: 'BYD', name: 'Boyd Gaming Corporation', exchange: 'NYSE' },
  { ticker: 'MGM', name: 'MGM Resorts International', exchange: 'NYSE' },
  { ticker: 'WYNN', name: 'Wynn Resorts Limited', exchange: 'NASDAQ' },
  { ticker: 'CZR', name: 'Caesars Entertainment Inc.', exchange: 'NASDAQ' },
  { ticker: 'LNW', name: 'Light & Wonder Inc.', exchange: 'NASDAQ' },
  { ticker: 'PINS', name: 'Pinterest Inc.', exchange: 'NYSE' },
  { ticker: 'SNAP', name: 'Snap Inc.', exchange: 'NYSE' },
  { ticker: 'BMBL', name: 'Bumble Inc.', exchange: 'NASDAQ' },
  { ticker: 'YELP', name: 'Yelp Inc.', exchange: 'NYSE' },
  { ticker: 'TRIP', name: 'TripAdvisor Inc.', exchange: 'NASDAQ' },
  { ticker: 'PTON', name: 'Peloton Interactive Inc.', exchange: 'NASDAQ' },
  { ticker: 'LULU', name: 'Lululemon Athletica Inc.', exchange: 'NASDAQ' },
  { ticker: 'YETI', name: 'YETI Holdings Inc.', exchange: 'NYSE' },
  { ticker: 'CROX', name: 'Crocs Inc.', exchange: 'NASDAQ' },
  { ticker: 'SKX', name: 'Skechers U.S.A. Inc.', exchange: 'NYSE' },
  { ticker: 'UAA', name: 'Under Armour Inc.', exchange: 'NYSE' },
  { ticker: 'LEVI', name: 'Levi Strauss & Co.', exchange: 'NYSE' },
  { ticker: 'VFC', name: 'V.F. Corporation', exchange: 'NYSE' },
  { ticker: 'CPRI', name: 'Capri Holdings Limited', exchange: 'NYSE' },
  { ticker: 'PVH', name: 'PVH Corp.', exchange: 'NYSE' },
  { ticker: 'HBI', name: 'Hanesbrands Inc.', exchange: 'NYSE' },
  { ticker: 'GOOS', name: 'Canada Goose Holdings Inc.', exchange: 'NYSE' },
  { ticker: 'EL', name: 'The Estée Lauder Companies Inc.', exchange: 'NYSE' },
  { ticker: 'CLX', name: 'The Clorox Company', exchange: 'NYSE' },
  { ticker: 'CHD', name: 'Church & Dwight Co. Inc.', exchange: 'NYSE' },
  { ticker: 'SPB', name: 'Spectrum Brands Holdings Inc.', exchange: 'NYSE' },
  { ticker: 'COTY', name: 'Coty Inc.', exchange: 'NYSE' },
  { ticker: 'ENR', name: 'Energizer Holdings Inc.', exchange: 'NYSE' },
  { ticker: 'CL', name: 'Colgate-Palmolive Company', exchange: 'NYSE' },
  { ticker: 'KMB', name: 'Kimberly-Clark Corporation', exchange: 'NYSE' },
  { ticker: 'PG', name: 'The Procter & Gamble Company', exchange: 'NYSE' },
  { ticker: 'ETSY', name: 'Etsy Inc.', exchange: 'NASDAQ' },
  { ticker: 'CHWY', name: 'Chewy Inc.', exchange: 'NYSE' },
  { ticker: 'W', name: 'Wayfair Inc.', exchange: 'NYSE' },
  { ticker: 'FTCH', name: 'Farfetch Limited', exchange: 'NYSE' },
  { ticker: 'REAL', name: 'The RealReal Inc.', exchange: 'NASDAQ' },
];
