// Russell 2000 Top 100 Small Cap Growth Leaders
export const RUSSELL_2000 = [
  { ticker: 'RXRX', name: 'Recursion Pharmaceuticals Inc.', exchange: 'NASDAQ' },
  { ticker: 'BROS', name: 'Dutch Bros Inc.', exchange: 'NYSE' },
  { ticker: 'CELH', name: 'Celsius Holdings Inc.', exchange: 'NASDAQ' },
  { ticker: 'SMCI', name: 'Super Micro Computer Inc.', exchange: 'NASDAQ' },
  { ticker: 'IONQ', name: 'IonQ Inc.', exchange: 'NYSE' },
  { ticker: 'CVNA', name: 'Carvana Co.', exchange: 'NYSE' },
  { ticker: 'TOST', name: 'Toast Inc.', exchange: 'NYSE' },
  { ticker: 'FOUR', name: 'Shift4 Payments Inc.', exchange: 'NYSE' },
  { ticker: 'SAIA', name: 'Saia Inc.', exchange: 'NASDAQ' },
  { ticker: 'WOLF', name: 'Wolfspeed Inc.', exchange: 'NYSE' },
  { ticker: 'VERX', name: 'Vertex Inc.', exchange: 'NASDAQ' },
  { ticker: 'BRBR', name: 'BellRing Brands Inc.', exchange: 'NYSE' },
  { ticker: 'QTWO', name: 'Q2 Holdings Inc.', exchange: 'NYSE' },
  { ticker: 'STEP', name: 'StepStone Group Inc.', exchange: 'NASDAQ' },
  { ticker: 'RH', name: 'RH (Restoration Hardware)', exchange: 'NYSE' },
  { ticker: 'AFRM', name: 'Affirm Holdings Inc.', exchange: 'NASDAQ' },
  { ticker: 'SOFI', name: 'SoFi Technologies Inc.', exchange: 'NASDAQ' },
  { ticker: 'UPST', name: 'Upstart Holdings Inc.', exchange: 'NASDAQ' },
  { ticker: 'LPLA', name: 'LPL Financial Holdings Inc.', exchange: 'NASDAQ' },
  { ticker: 'RBLX', name: 'Roblox Corporation', exchange: 'NYSE' },
  { ticker: 'U', name: 'Unity Software Inc.', exchange: 'NYSE' },
  { ticker: 'RIVN', name: 'Rivian Automotive Inc.', exchange: 'NASDAQ' },
  { ticker: 'LCID', name: 'Lucid Group Inc.', exchange: 'NASDAQ' },
  { ticker: 'XPEV', name: 'XPeng Inc.', exchange: 'NYSE' },
  { ticker: 'NIO', name: 'NIO Inc.', exchange: 'NYSE' },
  { ticker: 'LI', name: 'Li Auto Inc.', exchange: 'NASDAQ' },
  { ticker: 'PLUG', name: 'Plug Power Inc.', exchange: 'NASDAQ' },
  { ticker: 'FCEL', name: 'FuelCell Energy Inc.', exchange: 'NASDAQ' },
  { ticker: 'BLDP', name: 'Ballard Power Systems Inc.', exchange: 'NASDAQ' },
  { ticker: 'BE', name: 'Bloom Energy Corporation', exchange: 'NYSE' },
  { ticker: 'RUN', name: 'Sunrun Inc.', exchange: 'NASDAQ' },
  { ticker: 'NOVA', name: 'Sunnova Energy International Inc.', exchange: 'NYSE' },
  { ticker: 'ARRY', name: 'Array Technologies Inc.', exchange: 'NASDAQ' },
  { ticker: 'MAXN', name: 'Maxeon Solar Technologies Ltd.', exchange: 'NASDAQ' },
  { ticker: 'SHLS', name: 'Shoals Technologies Group Inc.', exchange: 'NASDAQ' },
  { ticker: 'VKTX', name: 'Viking Therapeutics Inc.', exchange: 'NASDAQ' },
  { ticker: 'SRRK', name: 'Scholar Rock Holding Corporation', exchange: 'NASDAQ' },
  { ticker: 'PRVA', name: 'Privia Health Group Inc.', exchange: 'NASDAQ' },
  { ticker: 'ACHR', name: 'Archer Aviation Inc.', exchange: 'NYSE' },
  { ticker: 'JOBY', name: 'Joby Aviation Inc.', exchange: 'NYSE' },
  { ticker: 'LILM', name: 'Lilium N.V.', exchange: 'NASDAQ' },
  { ticker: 'EVTL', name: 'Vertical Aerospace Ltd.', exchange: 'NYSE' },
  { ticker: 'BLDE', name: 'Blade Air Mobility Inc.', exchange: 'NASDAQ' },
  { ticker: 'BOWX', name: 'BowX Acquisition Corp.', exchange: 'NASDAQ' },
  { ticker: 'SPCE', name: 'Virgin Galactic Holdings Inc.', exchange: 'NYSE' },
  { ticker: 'RKLB', name: 'Rocket Lab USA Inc.', exchange: 'NASDAQ' },
  { ticker: 'ASTS', name: 'AST SpaceMobile Inc.', exchange: 'NASDAQ' },
  { ticker: 'LUNR', name: 'Intuitive Machines Inc.', exchange: 'NASDAQ' },
  { ticker: 'VORB', name: 'Virgin Orbit Holdings Inc.', exchange: 'NASDAQ' },
  { ticker: 'SATS', name: 'EchoStar Corporation', exchange: 'NASDAQ' },
  { ticker: 'GILT', name: 'Gilat Satellite Networks Ltd.', exchange: 'NASDAQ' },
  { ticker: 'VSAT', name: 'Viasat Inc.', exchange: 'NASDAQ' },
  { ticker: 'GSAT', name: 'Globalstar Inc.', exchange: 'NYSE' },
  { ticker: 'IRDM', name: 'Iridium Communications Inc.', exchange: 'NASDAQ' },
  { ticker: 'OKLO', name: 'Oklo Inc.', exchange: 'NYSE' },
  { ticker: 'SMR', name: 'NuScale Power Corporation', exchange: 'NYSE' },
  { ticker: 'LEU', name: 'Centrus Energy Corp.', exchange: 'NYSE' },
  { ticker: 'UUUU', name: 'Energy Fuels Inc.', exchange: 'NYSE' },
  { ticker: 'UEC', name: 'Uranium Energy Corp.', exchange: 'NYSE' },
  { ticker: 'CCJ', name: 'Cameco Corporation', exchange: 'NYSE' },
  { ticker: 'DNN', name: 'Denison Mines Corp.', exchange: 'NYSE' },
  { ticker: 'NXE', name: 'NexGen Energy Ltd.', exchange: 'NYSE' },
  { ticker: 'BWEN', name: 'Broadwind Inc.', exchange: 'NASDAQ' },
  { ticker: 'CLNE', name: 'Clean Energy Fuels Corp.', exchange: 'NASDAQ' },
  { ticker: 'CHPT', name: 'ChargePoint Holdings Inc.', exchange: 'NYSE' },
  { ticker: 'EVGO', name: 'EVgo Inc.', exchange: 'NASDAQ' },
  { ticker: 'BLNK', name: 'Blink Charging Co.', exchange: 'NASDAQ' },
  { ticker: 'VLTA', name: 'Volta Inc.', exchange: 'NYSE' },
  { ticker: 'QS', name: 'QuantumScape Corporation', exchange: 'NYSE' },
  { ticker: 'SES', name: 'SES AI Corporation', exchange: 'NYSE' },
  { ticker: 'SLDP', name: 'Solid Power Inc.', exchange: 'NASDAQ' },
  { ticker: 'ENVX', name: 'Enovix Corporation', exchange: 'NASDAQ' },
  { ticker: 'FREYR', name: 'FREYR Battery', exchange: 'NYSE' },
  { ticker: 'CBAT', name: 'CBAK Energy Technology Inc.', exchange: 'NASDAQ' },
  { ticker: 'LAC', name: 'Lithium Americas Corp.', exchange: 'NYSE' },
  { ticker: 'LTHM', name: 'Livent Corporation', exchange: 'NYSE' },
  { ticker: 'SQM', name: 'Sociedad Quimica y Minera de Chile S.A.', exchange: 'NYSE' },
  { ticker: 'PLL', name: 'Piedmont Lithium Inc.', exchange: 'NASDAQ' },
  { ticker: 'MP', name: 'MP Materials Corp.', exchange: 'NYSE' },
  { ticker: 'LITM', name: 'Snow Lake Resources Ltd.', exchange: 'NASDAQ' },
  { ticker: 'IONR', name: 'ioneer Ltd.', exchange: 'NASDAQ' },
  { ticker: 'RGTI', name: 'Rigetti Computing Inc.', exchange: 'NASDAQ' },
  { ticker: 'QUBT', name: 'Quantum Computing Inc.', exchange: 'NASDAQ' },
  { ticker: 'QBTS', name: 'D-Wave Quantum Inc.', exchange: 'NYSE' },
  { ticker: 'ARQQ', name: 'Arqit Quantum Inc.', exchange: 'NASDAQ' },
  { ticker: 'QMCO', name: 'Quantum Corporation', exchange: 'NASDAQ' },
  { ticker: 'AI', name: 'C3.ai Inc.', exchange: 'NYSE' },
  { ticker: 'BBAI', name: 'BigBear.ai Holdings Inc.', exchange: 'NYSE' },
  { ticker: 'SOUN', name: 'SoundHound AI Inc.', exchange: 'NASDAQ' },
  { ticker: 'PATH', name: 'UiPath Inc.', exchange: 'NYSE' },
  { ticker: 'AMBA', name: 'Ambarella Inc.', exchange: 'NASDAQ' },
  { ticker: 'GENI', name: 'Genius Sports Limited', exchange: 'NYSE' },
  { ticker: 'FUBO', name: 'fuboTV Inc.', exchange: 'NYSE' },
  { ticker: 'DKNG', name: 'DraftKings Inc.', exchange: 'NASDAQ' },
  { ticker: 'PENN', name: 'PENN Entertainment Inc.', exchange: 'NASDAQ' },
  { ticker: 'RSI', name: 'Rush Street Interactive Inc.', exchange: 'NYSE' },
  { ticker: 'CHDN', name: 'Churchill Downs Inc.', exchange: 'NASDAQ' },
];
