// Complete S&P 500 Universe (~500 stocks)
export const SP500_STOCKS = [
  // Mega Cap Tech & Communication
  { ticker: 'AAPL', name: 'Apple Inc.', exchange: 'NASDAQ' },
  { ticker: 'MSFT', name: 'Microsoft Corporation', exchange: 'NASDAQ' },
  { ticker: 'GOOGL', name: 'Alphabet Inc. Class A', exchange: 'NASDAQ' },
  { ticker: 'GOOG', name: 'Alphabet Inc. Class C', exchange: 'NASDAQ' },
  { ticker: 'AMZN', name: 'Amazon.com Inc.', exchange: 'NASDAQ' },
  { ticker: 'NVDA', name: 'NVIDIA Corporation', exchange: 'NASDAQ' },
  { ticker: 'META', name: 'Meta Platforms Inc.', exchange: 'NASDAQ' },
  { ticker: 'TSLA', name: 'Tesla Inc.', exchange: 'NASDAQ' },
  { ticker: 'BRK.B', name: 'Berkshire Hathaway Inc. Class B', exchange: 'NYSE' },
  { ticker: 'V', name: 'Visa Inc.', exchange: 'NYSE' },
  { ticker: 'MA', name: 'Mastercard Incorporated', exchange: 'NYSE' },
  { ticker: 'NFLX', name: 'Netflix Inc.', exchange: 'NASDAQ' },
  { ticker: 'DIS', name: 'The Walt Disney Company', exchange: 'NYSE' },
  { ticker: 'CMCSA', name: 'Comcast Corporation', exchange: 'NASDAQ' },
  { ticker: 'T', name: 'AT&T Inc.', exchange: 'NYSE' },
  { ticker: 'VZ', name: 'Verizon Communications Inc.', exchange: 'NYSE' },
  { ticker: 'TMUS', name: 'T-Mobile US Inc.', exchange: 'NASDAQ' },
  { ticker: 'ORCL', name: 'Oracle Corporation', exchange: 'NYSE' },
  { ticker: 'CSCO', name: 'Cisco Systems Inc.', exchange: 'NASDAQ' },
  { ticker: 'ADBE', name: 'Adobe Inc.', exchange: 'NASDAQ' },
  { ticker: 'CRM', name: 'Salesforce Inc.', exchange: 'NYSE' },
  { ticker: 'INTC', name: 'Intel Corporation', exchange: 'NASDAQ' },
  { ticker: 'AMD', name: 'Advanced Micro Devices Inc.', exchange: 'NASDAQ' },
  { ticker: 'QCOM', name: 'QUALCOMM Incorporated', exchange: 'NASDAQ' },
  { ticker: 'AVGO', name: 'Broadcom Inc.', exchange: 'NASDAQ' },
  { ticker: 'TXN', name: 'Texas Instruments Incorporated', exchange: 'NASDAQ' },
  { ticker: 'IBM', name: 'International Business Machines Corporation', exchange: 'NYSE' },
  { ticker: 'ACN', name: 'Accenture plc', exchange: 'NYSE' },
  { ticker: 'INTU', name: 'Intuit Inc.', exchange: 'NASDAQ' },
  { ticker: 'NOW', name: 'ServiceNow Inc.', exchange: 'NYSE' },
  
  // Financials
  { ticker: 'JPM', name: 'JPMorgan Chase & Co.', exchange: 'NYSE' },
  { ticker: 'BAC', name: 'Bank of America Corporation', exchange: 'NYSE' },
  { ticker: 'WFC', name: 'Wells Fargo & Company', exchange: 'NYSE' },
  { ticker: 'C', name: 'Citigroup Inc.', exchange: 'NYSE' },
  { ticker: 'GS', name: 'The Goldman Sachs Group Inc.', exchange: 'NYSE' },
  { ticker: 'MS', name: 'Morgan Stanley', exchange: 'NYSE' },
  { ticker: 'AXP', name: 'American Express Company', exchange: 'NYSE' },
  { ticker: 'BLK', name: 'BlackRock Inc.', exchange: 'NYSE' },
  { ticker: 'SCHW', name: 'The Charles Schwab Corporation', exchange: 'NYSE' },
  { ticker: 'CB', name: 'Chubb Limited', exchange: 'NYSE' },
  { ticker: 'PGR', name: 'The Progressive Corporation', exchange: 'NYSE' },
  { ticker: 'MMC', name: 'Marsh & McLennan Companies Inc.', exchange: 'NYSE' },
  { ticker: 'AIG', name: 'American International Group Inc.', exchange: 'NYSE' },
  { ticker: 'MET', name: 'MetLife Inc.', exchange: 'NYSE' },
  { ticker: 'PRU', name: 'Prudential Financial Inc.', exchange: 'NYSE' },
  { ticker: 'USB', name: 'U.S. Bancorp', exchange: 'NYSE' },
  { ticker: 'PNC', name: 'The PNC Financial Services Group Inc.', exchange: 'NYSE' },
  { ticker: 'TFC', name: 'Truist Financial Corporation', exchange: 'NYSE' },
  { ticker: 'COF', name: 'Capital One Financial Corporation', exchange: 'NYSE' },
  { ticker: 'BK', name: 'The Bank of New York Mellon Corporation', exchange: 'NYSE' },
  { ticker: 'STT', name: 'State Street Corporation', exchange: 'NYSE' },
  { ticker: 'SPGI', name: 'S&P Global Inc.', exchange: 'NYSE' },
  { ticker: 'ICE', name: 'Intercontinental Exchange Inc.', exchange: 'NYSE' },
  { ticker: 'CME', name: 'CME Group Inc.', exchange: 'NASDAQ' },
  { ticker: 'AON', name: 'Aon plc', exchange: 'NYSE' },
  { ticker: 'AJG', name: 'Arthur J. Gallagher & Co.', exchange: 'NYSE' },
  { ticker: 'ALL', name: 'The Allstate Corporation', exchange: 'NYSE' },
  { ticker: 'TRV', name: 'The Travelers Companies Inc.', exchange: 'NYSE' },
  { ticker: 'AFL', name: 'Aflac Incorporated', exchange: 'NYSE' },
  { ticker: 'FITB', name: 'Fifth Third Bancorp', exchange: 'NASDAQ' },
  { ticker: 'HBAN', name: 'Huntington Bancshares Incorporated', exchange: 'NASDAQ' },
  { ticker: 'RF', name: 'Regions Financial Corporation', exchange: 'NYSE' },
  { ticker: 'KEY', name: 'KeyCorp', exchange: 'NYSE' },
  { ticker: 'CFG', name: 'Citizens Financial Group Inc.', exchange: 'NYSE' },
  { ticker: 'MTB', name: 'M&T Bank Corporation', exchange: 'NYSE' },
  { ticker: 'NTRS', name: 'Northern Trust Corporation', exchange: 'NASDAQ' },
  { ticker: 'FRC', name: 'First Republic Bank', exchange: 'NYSE' },
  { ticker: 'TROW', name: 'T. Rowe Price Group Inc.', exchange: 'NASDAQ' },
  { ticker: 'BEN', name: 'Franklin Resources Inc.', exchange: 'NYSE' },
  { ticker: 'IVZ', name: 'Invesco Ltd.', exchange: 'NYSE' },
  
  // Healthcare
  { ticker: 'UNH', name: 'UnitedHealth Group Incorporated', exchange: 'NYSE' },
  { ticker: 'JNJ', name: 'Johnson & Johnson', exchange: 'NYSE' },
  { ticker: 'PFE', name: 'Pfizer Inc.', exchange: 'NYSE' },
  { ticker: 'ABBV', name: 'AbbVie Inc.', exchange: 'NYSE' },
  { ticker: 'MRK', name: 'Merck & Co. Inc.', exchange: 'NYSE' },
  { ticker: 'LLY', name: 'Eli Lilly and Company', exchange: 'NYSE' },
  { ticker: 'TMO', name: 'Thermo Fisher Scientific Inc.', exchange: 'NYSE' },
  { ticker: 'ABT', name: 'Abbott Laboratories', exchange: 'NYSE' },
  { ticker: 'DHR', name: 'Danaher Corporation', exchange: 'NYSE' },
  { ticker: 'BMY', name: 'Bristol-Myers Squibb Company', exchange: 'NYSE' },
  { ticker: 'AMGN', name: 'Amgen Inc.', exchange: 'NASDAQ' },
  { ticker: 'GILD', name: 'Gilead Sciences Inc.', exchange: 'NASDAQ' },
  { ticker: 'CVS', name: 'CVS Health Corporation', exchange: 'NYSE' },
  { ticker: 'CI', name: 'The Cigna Group', exchange: 'NYSE' },
  { ticker: 'ELV', name: 'Elevance Health Inc.', exchange: 'NYSE' },
  { ticker: 'HCA', name: 'HCA Healthcare Inc.', exchange: 'NYSE' },
  { ticker: 'MCK', name: 'McKesson Corporation', exchange: 'NYSE' },
  { ticker: 'CAH', name: 'Cardinal Health Inc.', exchange: 'NYSE' },
  { ticker: 'COR', name: 'Cencora Inc.', exchange: 'NYSE' },
  { ticker: 'ISRG', name: 'Intuitive Surgical Inc.', exchange: 'NASDAQ' },
  { ticker: 'REGN', name: 'Regeneron Pharmaceuticals Inc.', exchange: 'NASDAQ' },
  { ticker: 'VRTX', name: 'Vertex Pharmaceuticals Incorporated', exchange: 'NASDAQ' },
  { ticker: 'BSX', name: 'Boston Scientific Corporation', exchange: 'NYSE' },
  { ticker: 'SYK', name: 'Stryker Corporation', exchange: 'NYSE' },
  { ticker: 'MDT', name: 'Medtronic plc', exchange: 'NYSE' },
  { ticker: 'ZTS', name: 'Zoetis Inc.', exchange: 'NYSE' },
  { ticker: 'BDX', name: 'Becton Dickinson and Company', exchange: 'NYSE' },
  { ticker: 'EW', name: 'Edwards Lifesciences Corporation', exchange: 'NYSE' },
  { ticker: 'HUM', name: 'Humana Inc.', exchange: 'NYSE' },
  { ticker: 'IDXX', name: 'IDEXX Laboratories Inc.', exchange: 'NASDAQ' },
  { ticker: 'IQV', name: 'IQVIA Holdings Inc.', exchange: 'NYSE' },
  { ticker: 'A', name: 'Agilent Technologies Inc.', exchange: 'NYSE' },
  { ticker: 'BAX', name: 'Baxter International Inc.', exchange: 'NYSE' },
  { ticker: 'ALGN', name: 'Align Technology Inc.', exchange: 'NASDAQ' },
  { ticker: 'RMD', name: 'ResMed Inc.', exchange: 'NYSE' },
  { ticker: 'DXCM', name: 'DexCom Inc.', exchange: 'NASDAQ' },
  { ticker: 'MOH', name: 'Molina Healthcare Inc.', exchange: 'NYSE' },
  { ticker: 'CNC', name: 'Centene Corporation', exchange: 'NYSE' },
  { ticker: 'BIIB', name: 'Biogen Inc.', exchange: 'NASDAQ' },
  { ticker: 'ILMN', name: 'Illumina Inc.', exchange: 'NASDAQ' },
  { ticker: 'MRNA', name: 'Moderna Inc.', exchange: 'NASDAQ' },
  { ticker: 'TECH', name: 'Bio-Techne Corporation', exchange: 'NASDAQ' },
  { ticker: 'PKI', name: 'PerkinElmer Inc.', exchange: 'NYSE' },
  { ticker: 'MTD', name: 'Mettler-Toledo International Inc.', exchange: 'NYSE' },
  { ticker: 'WAT', name: 'Waters Corporation', exchange: 'NYSE' },
  { ticker: 'DGX', name: 'Quest Diagnostics Incorporated', exchange: 'NYSE' },
  { ticker: 'LH', name: 'Laboratory Corporation of America Holdings', exchange: 'NYSE' },
  { ticker: 'VTRS', name: 'Viatris Inc.', exchange: 'NASDAQ' },
  // CTLT removed - being acquired
  { ticker: 'DVA', name: 'DaVita Inc.', exchange: 'NYSE' },
  { ticker: 'HOLX', name: 'Hologic Inc.', exchange: 'NASDAQ' },
  { ticker: 'COO', name: 'The Cooper Companies Inc.', exchange: 'NYSE' },
  { ticker: 'PODD', name: 'Insulet Corporation', exchange: 'NASDAQ' },
  { ticker: 'HSIC', name: 'Henry Schein Inc.', exchange: 'NASDAQ' },
  { ticker: 'XRAY', name: 'DENTSPLY SIRONA Inc.', exchange: 'NASDAQ' },
  { ticker: 'UHS', name: 'Universal Health Services Inc.', exchange: 'NYSE' },
  { ticker: 'HRL', name: 'Hormel Foods Corporation', exchange: 'NYSE' },
  
  // Consumer Discretionary
  { ticker: 'HD', name: 'The Home Depot Inc.', exchange: 'NYSE' },
  { ticker: 'MCD', name: 'McDonald\'s Corporation', exchange: 'NYSE' },
  { ticker: 'NKE', name: 'NIKE Inc.', exchange: 'NYSE' },
  { ticker: 'SBUX', name: 'Starbucks Corporation', exchange: 'NASDAQ' },
  { ticker: 'LOW', name: 'Lowe\'s Companies Inc.', exchange: 'NYSE' },
  { ticker: 'TJX', name: 'The TJX Companies Inc.', exchange: 'NYSE' },
  { ticker: 'BKNG', name: 'Booking Holdings Inc.', exchange: 'NASDAQ' },
  { ticker: 'GM', name: 'General Motors Company', exchange: 'NYSE' },
  { ticker: 'F', name: 'Ford Motor Company', exchange: 'NYSE' },
  { ticker: 'MAR', name: 'Marriott International Inc.', exchange: 'NASDAQ' },
  { ticker: 'HLT', name: 'Hilton Worldwide Holdings Inc.', exchange: 'NYSE' },
  { ticker: 'CMG', name: 'Chipotle Mexican Grill Inc.', exchange: 'NYSE' },
  { ticker: 'ORLY', name: 'O\'Reilly Automotive Inc.', exchange: 'NASDAQ' },
  { ticker: 'AZO', name: 'AutoZone Inc.', exchange: 'NYSE' },
  { ticker: 'ROST', name: 'Ross Stores Inc.', exchange: 'NASDAQ' },
  { ticker: 'YUM', name: 'Yum! Brands Inc.', exchange: 'NYSE' },
  { ticker: 'LRCX', name: 'Lam Research Corporation', exchange: 'NASDAQ' },
  { ticker: 'AMAT', name: 'Applied Materials Inc.', exchange: 'NASDAQ' },
  { ticker: 'ADI', name: 'Analog Devices Inc.', exchange: 'NASDAQ' },
  { ticker: 'KLAC', name: 'KLA Corporation', exchange: 'NASDAQ' },
  { ticker: 'MCHP', name: 'Microchip Technology Incorporated', exchange: 'NASDAQ' },
  { ticker: 'SNPS', name: 'Synopsys Inc.', exchange: 'NASDAQ' },
  { ticker: 'CDNS', name: 'Cadence Design Systems Inc.', exchange: 'NASDAQ' },
  { ticker: 'LULU', name: 'Lululemon Athletica Inc.', exchange: 'NASDAQ' },
  { ticker: 'EBAY', name: 'eBay Inc.', exchange: 'NASDAQ' },
  { ticker: 'ABNB', name: 'Airbnb Inc.', exchange: 'NASDAQ' },
  { ticker: 'UBER', name: 'Uber Technologies Inc.', exchange: 'NYSE' },
  { ticker: 'BBY', name: 'Best Buy Co. Inc.', exchange: 'NYSE' },
  { ticker: 'TSCO', name: 'Tractor Supply Company', exchange: 'NASDAQ' },
  { ticker: 'DG', name: 'Dollar General Corporation', exchange: 'NYSE' },
  { ticker: 'DLTR', name: 'Dollar Tree Inc.', exchange: 'NASDAQ' },
  { ticker: 'TPR', name: 'Tapestry Inc.', exchange: 'NYSE' },
  { ticker: 'RL', name: 'Ralph Lauren Corporation', exchange: 'NYSE' },
  { ticker: 'NVR', name: 'NVR Inc.', exchange: 'NYSE' },
  { ticker: 'PHM', name: 'PulteGroup Inc.', exchange: 'NYSE' },
  { ticker: 'LEN', name: 'Lennar Corporation', exchange: 'NYSE' },
  { ticker: 'DHI', name: 'D.R. Horton Inc.', exchange: 'NYSE' },
  { ticker: 'GPC', name: 'Genuine Parts Company', exchange: 'NYSE' },
  { ticker: 'AAP', name: 'Advance Auto Parts Inc.', exchange: 'NYSE' },
  { ticker: 'GRMN', name: 'Garmin Ltd.', exchange: 'NASDAQ' },
  { ticker: 'BWA', name: 'BorgWarner Inc.', exchange: 'NYSE' },
  { ticker: 'WHR', name: 'Whirlpool Corporation', exchange: 'NYSE' },
  { ticker: 'HAS', name: 'Hasbro Inc.', exchange: 'NASDAQ' },
  { ticker: 'MAT', name: 'Mattel Inc.', exchange: 'NASDAQ' },
  { ticker: 'LVS', name: 'Las Vegas Sands Corp.', exchange: 'NYSE' },
  { ticker: 'WYNN', name: 'Wynn Resorts Limited', exchange: 'NASDAQ' },
  { ticker: 'MGM', name: 'MGM Resorts International', exchange: 'NYSE' },
  { ticker: 'POOL', name: 'Pool Corporation', exchange: 'NASDAQ' },
  { ticker: 'DRI', name: 'Darden Restaurants Inc.', exchange: 'NYSE' },
  { ticker: 'ULTA', name: 'Ulta Beauty Inc.', exchange: 'NASDAQ' },
  { ticker: 'LKQ', name: 'LKQ Corporation', exchange: 'NASDAQ' },
  { ticker: 'MHK', name: 'Mohawk Industries Inc.', exchange: 'NYSE' },
  { ticker: 'KMX', name: 'CarMax Inc.', exchange: 'NYSE' },
  { ticker: 'CZR', name: 'Caesars Entertainment Inc.', exchange: 'NASDAQ' },
  
  // Consumer Staples
  { ticker: 'PG', name: 'The Procter & Gamble Company', exchange: 'NYSE' },
  { ticker: 'KO', name: 'The Coca-Cola Company', exchange: 'NYSE' },
  { ticker: 'PEP', name: 'PepsiCo Inc.', exchange: 'NASDAQ' },
  { ticker: 'WMT', name: 'Walmart Inc.', exchange: 'NYSE' },
  { ticker: 'COST', name: 'Costco Wholesale Corporation', exchange: 'NASDAQ' },
  { ticker: 'PM', name: 'Philip Morris International Inc.', exchange: 'NYSE' },
  { ticker: 'MO', name: 'Altria Group Inc.', exchange: 'NYSE' },
  { ticker: 'CL', name: 'Colgate-Palmolive Company', exchange: 'NYSE' },
  { ticker: 'KMB', name: 'Kimberly-Clark Corporation', exchange: 'NYSE' },
  { ticker: 'GIS', name: 'General Mills Inc.', exchange: 'NYSE' },
  { ticker: 'K', name: 'Kellanova', exchange: 'NYSE' },
  { ticker: 'HSY', name: 'The Hershey Company', exchange: 'NYSE' },
  { ticker: 'MDLZ', name: 'Mondelez International Inc.', exchange: 'NASDAQ' },
  { ticker: 'KHC', name: 'The Kraft Heinz Company', exchange: 'NASDAQ' },
  { ticker: 'MNST', name: 'Monster Beverage Corporation', exchange: 'NASDAQ' },
  { ticker: 'STZ', name: 'Constellation Brands Inc.', exchange: 'NYSE' },
  { ticker: 'TAP', name: 'Molson Coors Beverage Company', exchange: 'NYSE' },
  { ticker: 'ADM', name: 'Archer-Daniels-Midland Company', exchange: 'NYSE' },
  { ticker: 'BG', name: 'Bunge Global SA', exchange: 'NYSE' },
  { ticker: 'TSN', name: 'Tyson Foods Inc.', exchange: 'NYSE' },
  { ticker: 'SJM', name: 'The J.M. Smucker Company', exchange: 'NYSE' },
  { ticker: 'CPB', name: 'Campbell Soup Company', exchange: 'NYSE' },
  { ticker: 'CAG', name: 'Conagra Brands Inc.', exchange: 'NYSE' },
  { ticker: 'KR', name: 'The Kroger Co.', exchange: 'NYSE' },
  { ticker: 'SYY', name: 'Sysco Corporation', exchange: 'NYSE' },
  { ticker: 'KDP', name: 'Keurig Dr Pepper Inc.', exchange: 'NASDAQ' },
  { ticker: 'KVUE', name: 'Kenvue Inc.', exchange: 'NYSE' },
  { ticker: 'EL', name: 'The Estée Lauder Companies Inc.', exchange: 'NYSE' },
  { ticker: 'CLX', name: 'The Clorox Company', exchange: 'NYSE' },
  { ticker: 'CHD', name: 'Church & Dwight Co. Inc.', exchange: 'NYSE' },
  { ticker: 'MKC', name: 'McCormick & Company Incorporated', exchange: 'NYSE' },
  
  // Energy
  { ticker: 'XOM', name: 'Exxon Mobil Corporation', exchange: 'NYSE' },
  { ticker: 'CVX', name: 'Chevron Corporation', exchange: 'NYSE' },
  { ticker: 'COP', name: 'ConocoPhillips', exchange: 'NYSE' },
  { ticker: 'SLB', name: 'Schlumberger N.V.', exchange: 'NYSE' },
  { ticker: 'EOG', name: 'EOG Resources Inc.', exchange: 'NYSE' },
  { ticker: 'MPC', name: 'Marathon Petroleum Corporation', exchange: 'NYSE' },
  { ticker: 'PSX', name: 'Phillips 66', exchange: 'NYSE' },
  { ticker: 'VLO', name: 'Valero Energy Corporation', exchange: 'NYSE' },
  { ticker: 'OXY', name: 'Occidental Petroleum Corporation', exchange: 'NYSE' },
  // HES removed - being acquired by Chevron
  { ticker: 'HAL', name: 'Halliburton Company', exchange: 'NYSE' },
  { ticker: 'BKR', name: 'Baker Hughes Company', exchange: 'NASDAQ' },
  { ticker: 'WMB', name: 'The Williams Companies Inc.', exchange: 'NYSE' },
  { ticker: 'KMI', name: 'Kinder Morgan Inc.', exchange: 'NYSE' },
  { ticker: 'OKE', name: 'ONEOK Inc.', exchange: 'NYSE' },
  { ticker: 'DVN', name: 'Devon Energy Corporation', exchange: 'NYSE' },
  { ticker: 'FANG', name: 'Diamondback Energy Inc.', exchange: 'NASDAQ' },
  { ticker: 'MRO', name: 'Marathon Oil Corporation', exchange: 'NYSE' },
  { ticker: 'APA', name: 'APA Corporation', exchange: 'NASDAQ' },
  { ticker: 'CTRA', name: 'Coterra Energy Inc.', exchange: 'NYSE' },
  { ticker: 'EQT', name: 'EQT Corporation', exchange: 'NYSE' },
  { ticker: 'TRGP', name: 'Targa Resources Corp.', exchange: 'NYSE' },
  { ticker: 'LNG', name: 'Cheniere Energy Inc.', exchange: 'NYSE' },
  
  // Industrials
  { ticker: 'BA', name: 'The Boeing Company', exchange: 'NYSE' },
  { ticker: 'CAT', name: 'Caterpillar Inc.', exchange: 'NYSE' },
  { ticker: 'HON', name: 'Honeywell International Inc.', exchange: 'NASDAQ' },
  { ticker: 'UPS', name: 'United Parcel Service Inc.', exchange: 'NYSE' },
  { ticker: 'RTX', name: 'RTX Corporation', exchange: 'NYSE' },
  { ticker: 'LMT', name: 'Lockheed Martin Corporation', exchange: 'NYSE' },
  { ticker: 'GE', name: 'GE Aerospace', exchange: 'NYSE' },
  { ticker: 'DE', name: 'Deere & Company', exchange: 'NYSE' },
  { ticker: 'MMM', name: '3M Company', exchange: 'NYSE' },
  { ticker: 'UNP', name: 'Union Pacific Corporation', exchange: 'NYSE' },
  { ticker: 'NSC', name: 'Norfolk Southern Corporation', exchange: 'NYSE' },
  { ticker: 'CSX', name: 'CSX Corporation', exchange: 'NASDAQ' },
  { ticker: 'FDX', name: 'FedEx Corporation', exchange: 'NYSE' },
  { ticker: 'WM', name: 'Waste Management Inc.', exchange: 'NYSE' },
  { ticker: 'EMR', name: 'Emerson Electric Co.', exchange: 'NYSE' },
  { ticker: 'ETN', name: 'Eaton Corporation plc', exchange: 'NYSE' },
  { ticker: 'ITW', name: 'Illinois Tool Works Inc.', exchange: 'NYSE' },
  { ticker: 'PH', name: 'Parker-Hannifin Corporation', exchange: 'NYSE' },
  { ticker: 'GD', name: 'General Dynamics Corporation', exchange: 'NYSE' },
  { ticker: 'NOC', name: 'Northrop Grumman Corporation', exchange: 'NYSE' },
  { ticker: 'LHX', name: 'L3Harris Technologies Inc.', exchange: 'NYSE' },
  { ticker: 'TXT', name: 'Textron Inc.', exchange: 'NYSE' },
  { ticker: 'ROK', name: 'Rockwell Automation Inc.', exchange: 'NYSE' },
  { ticker: 'CARR', name: 'Carrier Global Corporation', exchange: 'NYSE' },
  { ticker: 'OTIS', name: 'Otis Worldwide Corporation', exchange: 'NYSE' },
  { ticker: 'PCAR', name: 'PACCAR Inc.', exchange: 'NASDAQ' },
  { ticker: 'CMI', name: 'Cummins Inc.', exchange: 'NYSE' },
  { ticker: 'IR', name: 'Ingersoll Rand Inc.', exchange: 'NYSE' },
  { ticker: 'TDG', name: 'TransDigm Group Incorporated', exchange: 'NYSE' },
  { ticker: 'AME', name: 'AMETEK Inc.', exchange: 'NYSE' },
  { ticker: 'DOV', name: 'Dover Corporation', exchange: 'NYSE' },
  { ticker: 'FAST', name: 'Fastenal Company', exchange: 'NASDAQ' },
  { ticker: 'PWR', name: 'Quanta Services Inc.', exchange: 'NYSE' },
  { ticker: 'RSG', name: 'Republic Services Inc.', exchange: 'NYSE' },
  { ticker: 'VRSK', name: 'Verisk Analytics Inc.', exchange: 'NASDAQ' },
  { ticker: 'IEX', name: 'IDEX Corporation', exchange: 'NYSE' },
  { ticker: 'XYL', name: 'Xylem Inc.', exchange: 'NYSE' },
  { ticker: 'FTV', name: 'Fortive Corporation', exchange: 'NYSE' },
  { ticker: 'GNRC', name: 'Generac Holdings Inc.', exchange: 'NYSE' },
  { ticker: 'CPRT', name: 'Copart Inc.', exchange: 'NASDAQ' },
  { ticker: 'ODFL', name: 'Old Dominion Freight Line Inc.', exchange: 'NASDAQ' },
  { ticker: 'JBHT', name: 'J.B. Hunt Transport Services Inc.', exchange: 'NASDAQ' },
  { ticker: 'CHRW', name: 'C.H. Robinson Worldwide Inc.', exchange: 'NASDAQ' },
  { ticker: 'URI', name: 'United Rentals Inc.', exchange: 'NYSE' },
  { ticker: 'EXPD', name: 'Expeditors International of Washington Inc.', exchange: 'NASDAQ' },
  { ticker: 'PAYX', name: 'Paychex Inc.', exchange: 'NASDAQ' },
  { ticker: 'ADP', name: 'Automatic Data Processing Inc.', exchange: 'NASDAQ' },
  { ticker: 'J', name: 'Jacobs Solutions Inc.', exchange: 'NYSE' },
  { ticker: 'ALLE', name: 'Allegion plc', exchange: 'NYSE' },
  { ticker: 'BLDR', name: 'Builders FirstSource Inc.', exchange: 'NYSE' },
  { ticker: 'SNA', name: 'Snap-on Incorporated', exchange: 'NYSE' },
  { ticker: 'LDOS', name: 'Leidos Holdings Inc.', exchange: 'NYSE' },
  
  // Materials
  { ticker: 'LIN', name: 'Linde plc', exchange: 'NASDAQ' },
  { ticker: 'APD', name: 'Air Products and Chemicals Inc.', exchange: 'NYSE' },
  { ticker: 'SHW', name: 'The Sherwin-Williams Company', exchange: 'NYSE' },
  { ticker: 'ECL', name: 'Ecolab Inc.', exchange: 'NYSE' },
  { ticker: 'DD', name: 'DuPont de Nemours Inc.', exchange: 'NYSE' },
  { ticker: 'DOW', name: 'Dow Inc.', exchange: 'NYSE' },
  { ticker: 'NEM', name: 'Newmont Corporation', exchange: 'NYSE' },
  { ticker: 'FCX', name: 'Freeport-McMoRan Inc.', exchange: 'NYSE' },
  { ticker: 'NUE', name: 'Nucor Corporation', exchange: 'NYSE' },
  { ticker: 'VMC', name: 'Vulcan Materials Company', exchange: 'NYSE' },
  { ticker: 'MLM', name: 'Martin Marietta Materials Inc.', exchange: 'NYSE' },
  { ticker: 'CTVA', name: 'Corteva Inc.', exchange: 'NYSE' },
  { ticker: 'PPG', name: 'PPG Industries Inc.', exchange: 'NYSE' },
  { ticker: 'STLD', name: 'Steel Dynamics Inc.', exchange: 'NASDAQ' },
  { ticker: 'ALB', name: 'Albemarle Corporation', exchange: 'NYSE' },
  { ticker: 'CE', name: 'Celanese Corporation', exchange: 'NYSE' },
  { ticker: 'FMC', name: 'FMC Corporation', exchange: 'NYSE' },
  { ticker: 'EMN', name: 'Eastman Chemical Company', exchange: 'NYSE' },
  { ticker: 'MOS', name: 'The Mosaic Company', exchange: 'NYSE' },
  { ticker: 'CF', name: 'CF Industries Holdings Inc.', exchange: 'NYSE' },
  { ticker: 'IP', name: 'International Paper Company', exchange: 'NYSE' },
  { ticker: 'PKG', name: 'Packaging Corporation of America', exchange: 'NYSE' },
  { ticker: 'BALL', name: 'Ball Corporation', exchange: 'NYSE' },
  { ticker: 'AVY', name: 'Avery Dennison Corporation', exchange: 'NYSE' },
  { ticker: 'SEE', name: 'Sealed Air Corporation', exchange: 'NYSE' },
  
  // Real Estate
  { ticker: 'PLD', name: 'Prologis Inc.', exchange: 'NYSE' },
  { ticker: 'AMT', name: 'American Tower Corporation', exchange: 'NYSE' },
  { ticker: 'CCI', name: 'Crown Castle Inc.', exchange: 'NYSE' },
  { ticker: 'EQIX', name: 'Equinix Inc.', exchange: 'NASDAQ' },
  { ticker: 'PSA', name: 'Public Storage', exchange: 'NYSE' },
  { ticker: 'DLR', name: 'Digital Realty Trust Inc.', exchange: 'NYSE' },
  { ticker: 'WELL', name: 'Welltower Inc.', exchange: 'NYSE' },
  { ticker: 'SPG', name: 'Simon Property Group Inc.', exchange: 'NYSE' },
  { ticker: 'O', name: 'Realty Income Corporation', exchange: 'NYSE' },
  { ticker: 'VICI', name: 'VICI Properties Inc.', exchange: 'NYSE' },
  { ticker: 'AVB', name: 'AvalonBay Communities Inc.', exchange: 'NYSE' },
  { ticker: 'EQR', name: 'Equity Residential', exchange: 'NYSE' },
  { ticker: 'INVH', name: 'Invitation Homes Inc.', exchange: 'NYSE' },
  { ticker: 'MAA', name: 'Mid-America Apartment Communities Inc.', exchange: 'NYSE' },
  { ticker: 'ESS', name: 'Essex Property Trust Inc.', exchange: 'NYSE' },
  { ticker: 'VTR', name: 'Ventas Inc.', exchange: 'NYSE' },
  { ticker: 'ARE', name: 'Alexandria Real Estate Equities Inc.', exchange: 'NYSE' },
  { ticker: 'DOC', name: 'Physicians Realty Trust', exchange: 'NYSE' },
  { ticker: 'SBAC', name: 'SBA Communications Corporation', exchange: 'NASDAQ' },
  { ticker: 'EXR', name: 'Extra Space Storage Inc.', exchange: 'NYSE' },
  { ticker: 'CBRE', name: 'CBRE Group Inc.', exchange: 'NYSE' },
  { ticker: 'BXP', name: 'Boston Properties Inc.', exchange: 'NYSE' },
  { ticker: 'KIM', name: 'Kimco Realty Corporation', exchange: 'NYSE' },
  { ticker: 'REG', name: 'Regency Centers Corporation', exchange: 'NASDAQ' },
  { ticker: 'FRT', name: 'Federal Realty Investment Trust', exchange: 'NYSE' },
  { ticker: 'UDR', name: 'UDR Inc.', exchange: 'NYSE' },
  { ticker: 'CPT', name: 'Camden Property Trust', exchange: 'NYSE' },
  { ticker: 'HST', name: 'Host Hotels & Resorts Inc.', exchange: 'NASDAQ' },
  
  // Utilities
  { ticker: 'NEE', name: 'NextEra Energy Inc.', exchange: 'NYSE' },
  { ticker: 'DUK', name: 'Duke Energy Corporation', exchange: 'NYSE' },
  { ticker: 'SO', name: 'The Southern Company', exchange: 'NYSE' },
  { ticker: 'D', name: 'Dominion Energy Inc.', exchange: 'NYSE' },
  { ticker: 'AEP', name: 'American Electric Power Company Inc.', exchange: 'NASDAQ' },
  { ticker: 'EXC', name: 'Exelon Corporation', exchange: 'NASDAQ' },
  { ticker: 'SRE', name: 'Sempra', exchange: 'NYSE' },
  { ticker: 'XEL', name: 'Xcel Energy Inc.', exchange: 'NASDAQ' },
  { ticker: 'WEC', name: 'WEC Energy Group Inc.', exchange: 'NYSE' },
  { ticker: 'ED', name: 'Consolidated Edison Inc.', exchange: 'NYSE' },
  { ticker: 'EIX', name: 'Edison International', exchange: 'NYSE' },
  { ticker: 'ETR', name: 'Entergy Corporation', exchange: 'NYSE' },
  { ticker: 'DTE', name: 'DTE Energy Company', exchange: 'NYSE' },
  { ticker: 'PPL', name: 'PPL Corporation', exchange: 'NYSE' },
  { ticker: 'AEE', name: 'Ameren Corporation', exchange: 'NYSE' },
  { ticker: 'PEG', name: 'Public Service Enterprise Group Incorporated', exchange: 'NYSE' },
  { ticker: 'ES', name: 'Eversource Energy', exchange: 'NYSE' },
  { ticker: 'FE', name: 'FirstEnergy Corp.', exchange: 'NYSE' },
  { ticker: 'AWK', name: 'American Water Works Company Inc.', exchange: 'NYSE' },
  { ticker: 'ATO', name: 'Atmos Energy Corporation', exchange: 'NYSE' },
  { ticker: 'CMS', name: 'CMS Energy Corporation', exchange: 'NYSE' },
  { ticker: 'CNP', name: 'CenterPoint Energy Inc.', exchange: 'NYSE' },
  { ticker: 'NI', name: 'NiSource Inc.', exchange: 'NYSE' },
  { ticker: 'LNT', name: 'Alliant Energy Corporation', exchange: 'NASDAQ' },
  { ticker: 'EVRG', name: 'Evergy Inc.', exchange: 'NYSE' },
  { ticker: 'PNW', name: 'Pinnacle West Capital Corporation', exchange: 'NYSE' },
  { ticker: 'AES', name: 'The AES Corporation', exchange: 'NYSE' },
  
  // Additional S&P 500 Members
  { ticker: 'TGT', name: 'Target Corporation', exchange: 'NYSE' },
  { ticker: 'PYPL', name: 'PayPal Holdings Inc.', exchange: 'NASDAQ' },
  { ticker: 'SHOP', name: 'Shopify Inc.', exchange: 'NYSE' },
  { ticker: 'SQ', name: 'Block Inc.', exchange: 'NYSE' },
  { ticker: 'SNOW', name: 'Snowflake Inc.', exchange: 'NYSE' },
  { ticker: 'DDOG', name: 'Datadog Inc.', exchange: 'NASDAQ' },
  { ticker: 'ZM', name: 'Zoom Video Communications Inc.', exchange: 'NASDAQ' },
  { ticker: 'CRWD', name: 'CrowdStrike Holdings Inc.', exchange: 'NASDAQ' },
  { ticker: 'PANW', name: 'Palo Alto Networks Inc.', exchange: 'NASDAQ' },
  { ticker: 'FTNT', name: 'Fortinet Inc.', exchange: 'NASDAQ' },
  { ticker: 'ZS', name: 'Zscaler Inc.', exchange: 'NASDAQ' },
  { ticker: 'WDAY', name: 'Workday Inc.', exchange: 'NASDAQ' },
  { ticker: 'TEAM', name: 'Atlassian Corporation', exchange: 'NASDAQ' },
  { ticker: 'MDB', name: 'MongoDB Inc.', exchange: 'NASDAQ' },
  { ticker: 'NET', name: 'Cloudflare Inc.', exchange: 'NYSE' },
  { ticker: 'COIN', name: 'Coinbase Global Inc.', exchange: 'NASDAQ' },
  { ticker: 'ROKU', name: 'Roku Inc.', exchange: 'NASDAQ' },
  { ticker: 'SPOT', name: 'Spotify Technology S.A.', exchange: 'NYSE' },
  { ticker: 'TWLO', name: 'Twilio Inc.', exchange: 'NYSE' },
  { ticker: 'DOCU', name: 'DocuSign Inc.', exchange: 'NASDAQ' },
  { ticker: 'OKTA', name: 'Okta Inc.', exchange: 'NASDAQ' },
  // SPLK removed - acquired by Cisco
  
  // Major ETFs for benchmarking
  { ticker: 'SPY', name: 'SPDR S&P 500 ETF Trust', exchange: 'NYSE' },
  { ticker: 'QQQ', name: 'Invesco QQQ Trust', exchange: 'NASDAQ' },
  { ticker: 'IWM', name: 'iShares Russell 2000 ETF', exchange: 'NYSE' },
  { ticker: 'DIA', name: 'SPDR Dow Jones Industrial Average ETF Trust', exchange: 'NYSE' },
  { ticker: 'VOO', name: 'Vanguard S&P 500 ETF', exchange: 'NYSE' },
  { ticker: 'VTI', name: 'Vanguard Total Stock Market ETF', exchange: 'NYSE' },
  { ticker: 'AGG', name: 'iShares Core U.S. Aggregate Bond ETF', exchange: 'NYSE' },
  { ticker: 'BND', name: 'Vanguard Total Bond Market ETF', exchange: 'NASDAQ' },
  { ticker: 'GLD', name: 'SPDR Gold Trust', exchange: 'NYSE' },
  { ticker: 'SLV', name: 'iShares Silver Trust', exchange: 'NYSE' },
  { ticker: 'USO', name: 'United States Oil Fund', exchange: 'NYSE' },
  { ticker: 'UNG', name: 'United States Natural Gas Fund', exchange: 'NYSE' },
  { ticker: 'XLF', name: 'Financial Select Sector SPDR Fund', exchange: 'NYSE' },
  { ticker: 'XLK', name: 'Technology Select Sector SPDR Fund', exchange: 'NYSE' },
  { ticker: 'XLE', name: 'Energy Select Sector SPDR Fund', exchange: 'NYSE' },
  { ticker: 'XLV', name: 'Health Care Select Sector SPDR Fund', exchange: 'NYSE' },
  { ticker: 'XLI', name: 'Industrial Select Sector SPDR Fund', exchange: 'NYSE' },
  { ticker: 'XLB', name: 'Materials Select Sector SPDR Fund', exchange: 'NYSE' },
  { ticker: 'XLP', name: 'Consumer Staples Select Sector SPDR Fund', exchange: 'NYSE' },
  { ticker: 'XLY', name: 'Consumer Discretionary Select Sector SPDR Fund', exchange: 'NYSE' },
  { ticker: 'XLU', name: 'Utilities Select Sector SPDR Fund', exchange: 'NYSE' },
  { ticker: 'XLRE', name: 'Real Estate Select Sector SPDR Fund', exchange: 'NYSE' },
];
