// Full S&P 500 companies
export const SP500_STOCKS = [
  { ticker: 'AAPL', name: 'Apple Inc.', exchange: 'NASDAQ' },
  { ticker: 'MSFT', name: 'Microsoft Corporation', exchange: 'NASDAQ' },
  { ticker: 'GOOGL', name: 'Alphabet Inc. Class A', exchange: 'NASDAQ' },
  { ticker: 'GOOG', name: 'Alphabet Inc. Class C', exchange: 'NASDAQ' },
  { ticker: 'AMZN', name: 'Amazon.com Inc.', exchange: 'NASDAQ' },
  { ticker: 'NVDA', name: 'NVIDIA Corporation', exchange: 'NASDAQ' },
  { ticker: 'META', name: 'Meta Platforms Inc.', exchange: 'NASDAQ' },
  { ticker: 'TSLA', name: 'Tesla Inc.', exchange: 'NASDAQ' },
  { ticker: 'BRK.B', name: 'Berkshire Hathaway Inc. Class B', exchange: 'NYSE' },
  { ticker: 'LLY', name: 'Eli Lilly and Company', exchange: 'NYSE' },
  { ticker: 'JPM', name: 'JPMorgan Chase & Co.', exchange: 'NYSE' },
  { ticker: 'V', name: 'Visa Inc.', exchange: 'NYSE' },
  { ticker: 'UNH', name: 'UnitedHealth Group Inc.', exchange: 'NYSE' },
  { ticker: 'XOM', name: 'Exxon Mobil Corporation', exchange: 'NYSE' },
  { ticker: 'MA', name: 'Mastercard Inc.', exchange: 'NYSE' },
  { ticker: 'JNJ', name: 'Johnson & Johnson', exchange: 'NYSE' },
  { ticker: 'PG', name: 'Procter & Gamble Co.', exchange: 'NYSE' },
  { ticker: 'AVGO', name: 'Broadcom Inc.', exchange: 'NASDAQ' },
  { ticker: 'HD', name: 'The Home Depot Inc.', exchange: 'NYSE' },
  { ticker: 'CVX', name: 'Chevron Corporation', exchange: 'NYSE' },
  { ticker: 'MRK', name: 'Merck & Co. Inc.', exchange: 'NYSE' },
  { ticker: 'ABBV', name: 'AbbVie Inc.', exchange: 'NYSE' },
  { ticker: 'COST', name: 'Costco Wholesale Corporation', exchange: 'NASDAQ' },
  { ticker: 'KO', name: 'The Coca-Cola Company', exchange: 'NYSE' },
  { ticker: 'PEP', name: 'PepsiCo Inc.', exchange: 'NASDAQ' },
  { ticker: 'ADBE', name: 'Adobe Inc.', exchange: 'NASDAQ' },
  { ticker: 'CRM', name: 'Salesforce Inc.', exchange: 'NYSE' },
  { ticker: 'NFLX', name: 'Netflix Inc.', exchange: 'NASDAQ' },
  { ticker: 'TMO', name: 'Thermo Fisher Scientific Inc.', exchange: 'NYSE' },
  { ticker: 'MCD', name: 'McDonald\'s Corporation', exchange: 'NYSE' },
  { ticker: 'CSCO', name: 'Cisco Systems Inc.', exchange: 'NASDAQ' },
  { ticker: 'ABT', name: 'Abbott Laboratories', exchange: 'NYSE' },
  { ticker: 'WMT', name: 'Walmart Inc.', exchange: 'NYSE' },
  { ticker: 'DIS', name: 'The Walt Disney Company', exchange: 'NYSE' },
  { ticker: 'AMD', name: 'Advanced Micro Devices Inc.', exchange: 'NASDAQ' },
  { ticker: 'ORCL', name: 'Oracle Corporation', exchange: 'NYSE' },
  { ticker: 'ACN', name: 'Accenture plc', exchange: 'NYSE' },
  { ticker: 'INTC', name: 'Intel Corporation', exchange: 'NASDAQ' },
  { ticker: 'NKE', name: 'NIKE Inc.', exchange: 'NYSE' },
  { ticker: 'TXN', name: 'Texas Instruments Inc.', exchange: 'NASDAQ' },
  { ticker: 'DHR', name: 'Danaher Corporation', exchange: 'NYSE' },
  { ticker: 'PFE', name: 'Pfizer Inc.', exchange: 'NYSE' },
  { ticker: 'CMCSA', name: 'Comcast Corporation', exchange: 'NASDAQ' },
  { ticker: 'VZ', name: 'Verizon Communications Inc.', exchange: 'NYSE' },
  { ticker: 'LIN', name: 'Linde plc', exchange: 'NYSE' },
  { ticker: 'QCOM', name: 'QUALCOMM Inc.', exchange: 'NASDAQ' },
  { ticker: 'NEE', name: 'NextEra Energy Inc.', exchange: 'NYSE' },
  { ticker: 'PM', name: 'Philip Morris International Inc.', exchange: 'NYSE' },
  { ticker: 'UPS', name: 'United Parcel Service Inc.', exchange: 'NYSE' },
  { ticker: 'RTX', name: 'RTX Corporation', exchange: 'NYSE' },
  { ticker: 'T', name: 'AT&T Inc.', exchange: 'NYSE' },
  { ticker: 'INTU', name: 'Intuit Inc.', exchange: 'NASDAQ' },
  { ticker: 'HON', name: 'Honeywell International Inc.', exchange: 'NASDAQ' },
  { ticker: 'COP', name: 'ConocoPhillips', exchange: 'NYSE' },
  { ticker: 'SPGI', name: 'S&P Global Inc.', exchange: 'NYSE' },
  { ticker: 'UNP', name: 'Union Pacific Corporation', exchange: 'NYSE' },
  { ticker: 'LOW', name: 'Lowe\'s Companies Inc.', exchange: 'NYSE' },
  { ticker: 'BMY', name: 'Bristol-Myers Squibb Company', exchange: 'NYSE' },
  { ticker: 'AMGN', name: 'Amgen Inc.', exchange: 'NASDAQ' },
  { ticker: 'BA', name: 'The Boeing Company', exchange: 'NYSE' },
  { ticker: 'AXP', name: 'American Express Company', exchange: 'NYSE' },
  { ticker: 'SBUX', name: 'Starbucks Corporation', exchange: 'NASDAQ' },
  { ticker: 'CAT', name: 'Caterpillar Inc.', exchange: 'NYSE' },
  { ticker: 'BLK', name: 'BlackRock Inc.', exchange: 'NYSE' },
  { ticker: 'DE', name: 'Deere & Company', exchange: 'NYSE' },
  { ticker: 'GE', name: 'General Electric Company', exchange: 'NYSE' },
  { ticker: 'ADP', name: 'Automatic Data Processing Inc.', exchange: 'NASDAQ' },
  { ticker: 'GILD', name: 'Gilead Sciences Inc.', exchange: 'NASDAQ' },
  { ticker: 'BKNG', name: 'Booking Holdings Inc.', exchange: 'NASDAQ' },
  { ticker: 'MDLZ', name: 'Mondelez International Inc.', exchange: 'NASDAQ' },
  { ticker: 'MMC', name: 'Marsh & McLennan Companies Inc.', exchange: 'NYSE' },
  { ticker: 'TGT', name: 'Target Corporation', exchange: 'NYSE' },
  { ticker: 'AMT', name: 'American Tower Corporation', exchange: 'NYSE' },
  { ticker: 'VRTX', name: 'Vertex Pharmaceuticals Inc.', exchange: 'NASDAQ' },
  { ticker: 'ADI', name: 'Analog Devices Inc.', exchange: 'NASDAQ' },
  { ticker: 'NOW', name: 'ServiceNow Inc.', exchange: 'NYSE' },
  { ticker: 'C', name: 'Citigroup Inc.', exchange: 'NYSE' },
  { ticker: 'CVS', name: 'CVS Health Corporation', exchange: 'NYSE' },
  { ticker: 'ISRG', name: 'Intuitive Surgical Inc.', exchange: 'NASDAQ' },
  { ticker: 'CI', name: 'Cigna Corporation', exchange: 'NYSE' },
  { ticker: 'SCHW', name: 'The Charles Schwab Corporation', exchange: 'NYSE' },
  { ticker: 'REGN', name: 'Regeneron Pharmaceuticals Inc.', exchange: 'NASDAQ' },
  { ticker: 'ZTS', name: 'Zoetis Inc.', exchange: 'NYSE' },
  { ticker: 'PLD', name: 'Prologis Inc.', exchange: 'NYSE' },
  { ticker: 'MO', name: 'Altria Group Inc.', exchange: 'NYSE' },
  { ticker: 'AMAT', name: 'Applied Materials Inc.', exchange: 'NASDAQ' },
  { ticker: 'TMUS', name: 'T-Mobile US Inc.', exchange: 'NASDAQ' },
  { ticker: 'SYK', name: 'Stryker Corporation', exchange: 'NYSE' },
  { ticker: 'BSX', name: 'Boston Scientific Corporation', exchange: 'NYSE' },
  { ticker: 'CB', name: 'Chubb Limited', exchange: 'NYSE' },
  { ticker: 'MU', name: 'Micron Technology Inc.', exchange: 'NASDAQ' },
  { ticker: 'SO', name: 'The Southern Company', exchange: 'NYSE' },
  { ticker: 'DUK', name: 'Duke Energy Corporation', exchange: 'NYSE' },
  { ticker: 'LRCX', name: 'Lam Research Corporation', exchange: 'NASDAQ' },
  { ticker: 'BDX', name: 'Becton Dickinson and Company', exchange: 'NYSE' },
  { ticker: 'PANW', name: 'Palo Alto Networks Inc.', exchange: 'NASDAQ' },
  { ticker: 'EQIX', name: 'Equinix Inc.', exchange: 'NASDAQ' },
  { ticker: 'SLB', name: 'Schlumberger Limited', exchange: 'NYSE' },
  { ticker: 'PGR', name: 'The Progressive Corporation', exchange: 'NYSE' },
  { ticker: 'KLAC', name: 'KLA Corporation', exchange: 'NASDAQ' },
  { ticker: 'WM', name: 'Waste Management Inc.', exchange: 'NYSE' },
  { ticker: 'TJX', name: 'The TJX Companies Inc.', exchange: 'NYSE' },
  { ticker: 'ITW', name: 'Illinois Tool Works Inc.', exchange: 'NYSE' },
  { ticker: 'MS', name: 'Morgan Stanley', exchange: 'NYSE' },
  { ticker: 'GS', name: 'The Goldman Sachs Group Inc.', exchange: 'NYSE' },
  { ticker: 'APH', name: 'Amphenol Corporation', exchange: 'NYSE' },
  { ticker: 'SNPS', name: 'Synopsys Inc.', exchange: 'NASDAQ' },
  { ticker: 'MCO', name: 'Moody\'s Corporation', exchange: 'NYSE' },
  { ticker: 'USB', name: 'U.S. Bancorp', exchange: 'NYSE' },
  { ticker: 'NSC', name: 'Norfolk Southern Corporation', exchange: 'NYSE' },
  { ticker: 'FI', name: 'Fiserv Inc.', exchange: 'NYSE' },
  { ticker: 'CDNS', name: 'Cadence Design Systems Inc.', exchange: 'NASDAQ' },
  { ticker: 'AON', name: 'Aon plc', exchange: 'NYSE' },
  { ticker: 'ETN', name: 'Eaton Corporation plc', exchange: 'NYSE' },
  { ticker: 'CSX', name: 'CSX Corporation', exchange: 'NASDAQ' },
  { ticker: 'CME', name: 'CME Group Inc.', exchange: 'NASDAQ' },
  { ticker: 'WELL', name: 'Welltower Inc.', exchange: 'NYSE' },
  { ticker: 'SHW', name: 'The Sherwin-Williams Company', exchange: 'NYSE' },
  { ticker: 'CCI', name: 'Crown Castle Inc.', exchange: 'NYSE' },
  { ticker: 'ICE', name: 'Intercontinental Exchange Inc.', exchange: 'NYSE' },
  { ticker: 'TT', name: 'Trane Technologies plc', exchange: 'NYSE' },
  { ticker: 'PH', name: 'Parker-Hannifin Corporation', exchange: 'NYSE' },
  { ticker: 'PSX', name: 'Phillips 66', exchange: 'NYSE' },
  { ticker: 'NXPI', name: 'NXP Semiconductors N.V.', exchange: 'NASDAQ' },
  { ticker: 'MAR', name: 'Marriott International Inc.', exchange: 'NASDAQ' },
  { ticker: 'ADSK', name: 'Autodesk Inc.', exchange: 'NASDAQ' },
  { ticker: 'MRVL', name: 'Marvell Technology Inc.', exchange: 'NASDAQ' },
  { ticker: 'AJG', name: 'Arthur J. Gallagher & Co.', exchange: 'NYSE' },
  { ticker: 'MCK', name: 'McKesson Corporation', exchange: 'NYSE' },
  { ticker: 'ABNB', name: 'Airbnb Inc.', exchange: 'NASDAQ' },
  { ticker: 'ROP', name: 'Roper Technologies Inc.', exchange: 'NASDAQ' },
  { ticker: 'WMB', name: 'The Williams Companies Inc.', exchange: 'NYSE' },
  { ticker: 'HCA', name: 'HCA Healthcare Inc.', exchange: 'NYSE' },
  { ticker: 'CRWD', name: 'CrowdStrike Holdings Inc.', exchange: 'NASDAQ' },
  { ticker: 'FTNT', name: 'Fortinet Inc.', exchange: 'NASDAQ' },
  { ticker: 'PLTR', name: 'Palantir Technologies Inc.', exchange: 'NYSE' },
  { ticker: 'CARR', name: 'Carrier Global Corporation', exchange: 'NYSE' },
  { ticker: 'BK', name: 'The Bank of New York Mellon Corporation', exchange: 'NYSE' },
  { ticker: 'MNST', name: 'Monster Beverage Corporation', exchange: 'NASDAQ' },
  { ticker: 'EMR', name: 'Emerson Electric Co.', exchange: 'NYSE' },
  { ticker: 'PCAR', name: 'PACCAR Inc.', exchange: 'NASDAQ' },
  { ticker: 'CPRT', name: 'Copart Inc.', exchange: 'NASDAQ' },
  { ticker: 'O', name: 'Realty Income Corporation', exchange: 'NYSE' },
  { ticker: 'MCHP', name: 'Microchip Technology Inc.', exchange: 'NASDAQ' },
  { ticker: 'APO', name: 'Apollo Global Management Inc.', exchange: 'NYSE' },
  { ticker: 'AFL', name: 'Aflac Inc.', exchange: 'NYSE' },
  { ticker: 'MSI', name: 'Motorola Solutions Inc.', exchange: 'NYSE' },
  { ticker: 'ALL', name: 'The Allstate Corporation', exchange: 'NYSE' },
  { ticker: 'AIG', name: 'American International Group Inc.', exchange: 'NYSE' },
  { ticker: 'GM', name: 'General Motors Company', exchange: 'NYSE' },
  { ticker: 'OKE', name: 'ONEOK Inc.', exchange: 'NYSE' },
  { ticker: 'SPG', name: 'Simon Property Group Inc.', exchange: 'NYSE' },
  { ticker: 'PSA', name: 'Public Storage', exchange: 'NYSE' },
  { ticker: 'ORLY', name: 'O\'Reilly Automotive Inc.', exchange: 'NASDAQ' },
  { ticker: 'TRV', name: 'The Travelers Companies Inc.', exchange: 'NYSE' },
  { ticker: 'NEM', name: 'Newmont Corporation', exchange: 'NYSE' },
  { ticker: 'HLT', name: 'Hilton Worldwide Holdings Inc.', exchange: 'NYSE' },
  { ticker: 'PAYX', name: 'Paychex Inc.', exchange: 'NASDAQ' },
  { ticker: 'ROST', name: 'Ross Stores Inc.', exchange: 'NASDAQ' },
  { ticker: 'AZO', name: 'AutoZone Inc.', exchange: 'NYSE' },
  { ticker: 'SRE', name: 'Sempra', exchange: 'NYSE' },
  { ticker: 'KMB', name: 'Kimberly-Clark Corporation', exchange: 'NYSE' },
  { ticker: 'AEP', name: 'American Electric Power Company Inc.', exchange: 'NASDAQ' },
  { ticker: 'ODFL', name: 'Old Dominion Freight Line Inc.', exchange: 'NASDAQ' },
  { ticker: 'TEL', name: 'TE Connectivity Ltd.', exchange: 'NYSE' },
  { ticker: 'D', name: 'Dominion Energy Inc.', exchange: 'NYSE' },
  { ticker: 'CL', name: 'Colgate-Palmolive Company', exchange: 'NYSE' },
  { ticker: 'EW', name: 'Edwards Lifesciences Corporation', exchange: 'NYSE' },
  { ticker: 'GWW', name: 'W.W. Grainger Inc.', exchange: 'NYSE' },
  { ticker: 'HES', name: 'Hess Corporation', exchange: 'NYSE' },
  { ticker: 'TFC', name: 'Truist Financial Corporation', exchange: 'NYSE' },
  { ticker: 'A', name: 'Agilent Technologies Inc.', exchange: 'NYSE' },
  { ticker: 'CTAS', name: 'Cintas Corporation', exchange: 'NASDAQ' },
  { ticker: 'PCG', name: 'PG&E Corporation', exchange: 'NYSE' },
  { ticker: 'BKR', name: 'Baker Hughes Company', exchange: 'NASDAQ' },
  { ticker: 'KMI', name: 'Kinder Morgan Inc.', exchange: 'NYSE' },
  { ticker: 'DASH', name: 'DoorDash Inc.', exchange: 'NASDAQ' },
  { ticker: 'ECL', name: 'Ecolab Inc.', exchange: 'NYSE' },
  { ticker: 'FAST', name: 'Fastenal Company', exchange: 'NASDAQ' },
  { ticker: 'JCI', name: 'Johnson Controls International plc', exchange: 'NYSE' },
  { ticker: 'RSG', name: 'Republic Services Inc.', exchange: 'NYSE' },
  { ticker: 'GIS', name: 'General Mills Inc.', exchange: 'NYSE' },
  { ticker: 'XEL', name: 'Xcel Energy Inc.', exchange: 'NASDAQ' },
  { ticker: 'IDXX', name: 'IDEXX Laboratories Inc.', exchange: 'NASDAQ' },
  { ticker: 'DXCM', name: 'DexCom Inc.', exchange: 'NASDAQ' },
  { ticker: 'DD', name: 'DuPont de Nemours Inc.', exchange: 'NYSE' },
  { ticker: 'CMG', name: 'Chipotle Mexican Grill Inc.', exchange: 'NYSE' },
  { ticker: 'YUM', name: 'Yum! Brands Inc.', exchange: 'NYSE' },
  { ticker: 'ACGL', name: 'Arch Capital Group Ltd.', exchange: 'NASDAQ' },
  { ticker: 'EOG', name: 'EOG Resources Inc.', exchange: 'NYSE' },
  { ticker: 'KHC', name: 'The Kraft Heinz Company', exchange: 'NASDAQ' },
  { ticker: 'WEC', name: 'WEC Energy Group Inc.', exchange: 'NYSE' },
  { ticker: 'CTVA', name: 'Corteva Inc.', exchange: 'NYSE' },
  { ticker: 'VICI', name: 'VICI Properties Inc.', exchange: 'NYSE' },
  { ticker: 'VMC', name: 'Vulcan Materials Company', exchange: 'NYSE' },
  { ticker: 'KVUE', name: 'Kenvue Inc.', exchange: 'NYSE' },
  { ticker: 'STZ', name: 'Constellation Brands Inc.', exchange: 'NYSE' },
  { ticker: 'ON', name: 'ON Semiconductor Corporation', exchange: 'NASDAQ' },
  { ticker: 'EA', name: 'Electronic Arts Inc.', exchange: 'NASDAQ' },
  { ticker: 'BRO', name: 'Brown & Brown Inc.', exchange: 'NYSE' },
  { ticker: 'MLM', name: 'Martin Marietta Materials Inc.', exchange: 'NYSE' },
  { ticker: 'ED', name: 'Consolidated Edison Inc.', exchange: 'NYSE' },
  { ticker: 'EXC', name: 'Exelon Corporation', exchange: 'NASDAQ' },
  { ticker: 'AWK', name: 'American Water Works Company Inc.', exchange: 'NYSE' },
  { ticker: 'LHX', name: 'L3Harris Technologies Inc.', exchange: 'NYSE' },
  { ticker: 'PRU', name: 'Prudential Financial Inc.', exchange: 'NYSE' },
  { ticker: 'KR', name: 'The Kroger Co.', exchange: 'NYSE' },
  { ticker: 'IQV', name: 'IQVIA Holdings Inc.', exchange: 'NYSE' },
  { ticker: 'ROK', name: 'Rockwell Automation Inc.', exchange: 'NYSE' },
  { ticker: 'RMD', name: 'ResMed Inc.', exchange: 'NYSE' },
  { ticker: 'CBRE', name: 'CBRE Group Inc.', exchange: 'NYSE' },
  { ticker: 'PEG', name: 'Public Service Enterprise Group Inc.', exchange: 'NYSE' },
  { ticker: 'KEYS', name: 'Keysight Technologies Inc.', exchange: 'NYSE' },
  { ticker: 'GLW', name: 'Corning Inc.', exchange: 'NYSE' },
  { ticker: 'EL', name: 'The Estée Lauder Companies Inc.', exchange: 'NYSE' },
  { ticker: 'HAL', name: 'Halliburton Company', exchange: 'NYSE' },
  { ticker: 'EIX', name: 'Edison International', exchange: 'NYSE' },
  { ticker: 'IT', name: 'Gartner Inc.', exchange: 'NYSE' },
  { ticker: 'DLR', name: 'Digital Realty Trust Inc.', exchange: 'NYSE' },
  { ticker: 'AMP', name: 'Ameriprise Financial Inc.', exchange: 'NYSE' },
  { ticker: 'DOW', name: 'Dow Inc.', exchange: 'NYSE' },
  { ticker: 'DVN', name: 'Devon Energy Corporation', exchange: 'NYSE' },
  { ticker: 'FANG', name: 'Diamondback Energy Inc.', exchange: 'NASDAQ' },
  { ticker: 'PPG', name: 'PPG Industries Inc.', exchange: 'NYSE' },
  { ticker: 'GEHC', name: 'GE HealthCare Technologies Inc.', exchange: 'NASDAQ' },
  { ticker: 'HSY', name: 'The Hershey Company', exchange: 'NYSE' },
  { ticker: 'LMT', name: 'Lockheed Martin Corporation', exchange: 'NYSE' },
  { ticker: 'COR', name: 'Cencora Inc.', exchange: 'NYSE' },
  { ticker: 'DHI', name: 'D.R. Horton Inc.', exchange: 'NYSE' },
  { ticker: 'EXR', name: 'Extra Space Storage Inc.', exchange: 'NYSE' },
  { ticker: 'IR', name: 'Ingersoll Rand Inc.', exchange: 'NYSE' },
  { ticker: 'MTD', name: 'Mettler-Toledo International Inc.', exchange: 'NYSE' },
  { ticker: 'COF', name: 'Capital One Financial Corporation', exchange: 'NYSE' },
  { ticker: 'ANSS', name: 'ANSYS Inc.', exchange: 'NASDAQ' },
  { ticker: 'DFS', name: 'Discover Financial Services', exchange: 'NYSE' },
  { ticker: 'MTB', name: 'M&T Bank Corporation', exchange: 'NYSE' },
  { ticker: 'FDX', name: 'FedEx Corporation', exchange: 'NYSE' },
  { ticker: 'AVB', name: 'AvalonBay Communities Inc.', exchange: 'NYSE' },
  { ticker: 'GPN', name: 'Global Payments Inc.', exchange: 'NYSE' },
  { ticker: 'HIG', name: 'The Hartford Financial Services Group Inc.', exchange: 'NYSE' },
  { ticker: 'HPQ', name: 'HP Inc.', exchange: 'NYSE' },
  { ticker: 'EQR', name: 'Equity Residential', exchange: 'NYSE' },
  { ticker: 'WAB', name: 'Westinghouse Air Brake Technologies Corporation', exchange: 'NYSE' },
  { ticker: 'GRMN', name: 'Garmin Ltd.', exchange: 'NYSE' },
  { ticker: 'RCL', name: 'Royal Caribbean Cruises Ltd.', exchange: 'NYSE' },
  { ticker: 'SYY', name: 'Sysco Corporation', exchange: 'NYSE' },
  { ticker: 'TSN', name: 'Tyson Foods Inc.', exchange: 'NYSE' },
  { ticker: 'URI', name: 'United Rentals Inc.', exchange: 'NYSE' },
  { ticker: 'VLO', name: 'Valero Energy Corporation', exchange: 'NYSE' },
  { ticker: 'CHD', name: 'Church & Dwight Co. Inc.', exchange: 'NYSE' },
  { ticker: 'TTWO', name: 'Take-Two Interactive Software Inc.', exchange: 'NASDAQ' },
  { ticker: 'DAL', name: 'Delta Air Lines Inc.', exchange: 'NYSE' },
  { ticker: 'VLTO', name: 'Veralto Corporation', exchange: 'NYSE' },
  { ticker: 'SYF', name: 'Synchrony Financial', exchange: 'NYSE' },
  { ticker: 'ALB', name: 'Albemarle Corporation', exchange: 'NYSE' },
  { ticker: 'EFX', name: 'Equifax Inc.', exchange: 'NYSE' },
  { ticker: 'HPE', name: 'Hewlett Packard Enterprise Company', exchange: 'NYSE' },
  { ticker: 'NUE', name: 'Nucor Corporation', exchange: 'NYSE' },
  { ticker: 'PWR', name: 'Quanta Services Inc.', exchange: 'NYSE' },
  { ticker: 'MKC', name: 'McCormick & Company Inc.', exchange: 'NYSE' },
  { ticker: 'WBD', name: 'Warner Bros. Discovery Inc.', exchange: 'NASDAQ' },
  { ticker: 'AXON', name: 'Axon Enterprise Inc.', exchange: 'NASDAQ' },
  { ticker: 'CAH', name: 'Cardinal Health Inc.', exchange: 'NYSE' },
  { ticker: 'FITB', name: 'Fifth Third Bancorp', exchange: 'NASDAQ' },
  { ticker: 'LEN', name: 'Lennar Corporation', exchange: 'NYSE' },
  { ticker: 'NDAQ', name: 'Nasdaq Inc.', exchange: 'NASDAQ' },
  { ticker: 'PPL', name: 'PPL Corporation', exchange: 'NYSE' },
  { ticker: 'VRSK', name: 'Verisk Analytics Inc.', exchange: 'NASDAQ' },
  { ticker: 'WTW', name: 'Willis Towers Watson Public Limited Company', exchange: 'NASDAQ' },
  { ticker: 'ZBH', name: 'Zimmer Biomet Holdings Inc.', exchange: 'NYSE' },
  { ticker: 'DLTR', name: 'Dollar Tree Inc.', exchange: 'NASDAQ' },
  { ticker: 'IFF', name: 'International Flavors & Fragrances Inc.', exchange: 'NYSE' },
  { ticker: 'LVS', name: 'Las Vegas Sands Corp.', exchange: 'NYSE' },
  { ticker: 'NTRS', name: 'Northern Trust Corporation', exchange: 'NASDAQ' },
  { ticker: 'TRGP', name: 'Targa Resources Corp.', exchange: 'NYSE' },
  { ticker: 'BALL', name: 'Ball Corporation', exchange: 'NYSE' },
  { ticker: 'BBY', name: 'Best Buy Co. Inc.', exchange: 'NYSE' },
  { ticker: 'CBOE', name: 'Cboe Global Markets Inc.', exchange: 'NASDAQ' },
  { ticker: 'HBAN', name: 'Huntington Bancshares Inc.', exchange: 'NASDAQ' },
  { ticker: 'KEY', name: 'KeyCorp', exchange: 'NYSE' },
  { ticker: 'LYB', name: 'LyondellBasell Industries N.V.', exchange: 'NYSE' },
  { ticker: 'MPWR', name: 'Monolithic Power Systems Inc.', exchange: 'NASDAQ' },
  { ticker: 'RJF', name: 'Raymond James Financial Inc.', exchange: 'NYSE' },
  { ticker: 'SBAC', name: 'SBA Communications Corporation', exchange: 'NASDAQ' },
  { ticker: 'TYL', name: 'Tyler Technologies Inc.', exchange: 'NYSE' },
  { ticker: 'AVY', name: 'Avery Dennison Corporation', exchange: 'NYSE' },
  { ticker: 'AES', name: 'The AES Corporation', exchange: 'NYSE' },
  { ticker: 'ARE', name: 'Alexandria Real Estate Equities Inc.', exchange: 'NYSE' },
  { ticker: 'CFG', name: 'Citizens Financial Group Inc.', exchange: 'NYSE' },
  { ticker: 'CE', name: 'Celanese Corporation', exchange: 'NYSE' },
  { ticker: 'CNP', name: 'CenterPoint Energy Inc.', exchange: 'NYSE' },
  { ticker: 'DOV', name: 'Dover Corporation', exchange: 'NYSE' },
  { ticker: 'DRI', name: 'Darden Restaurants Inc.', exchange: 'NYSE' },
  { ticker: 'ESS', name: 'Essex Property Trust Inc.', exchange: 'NYSE' },
  { ticker: 'EBAY', name: 'eBay Inc.', exchange: 'NASDAQ' },
  { ticker: 'EQT', name: 'EQT Corporation', exchange: 'NYSE' },
  { ticker: 'EXPD', name: 'Expeditors International of Washington Inc.', exchange: 'NASDAQ' },
  { ticker: 'FE', name: 'FirstEnergy Corp.', exchange: 'NYSE' },
  { ticker: 'GDDY', name: 'GoDaddy Inc.', exchange: 'NYSE' },
  { ticker: 'HUBB', name: 'Hubbell Inc.', exchange: 'NYSE' },
  { ticker: 'HOLX', name: 'Hologic Inc.', exchange: 'NASDAQ' },
  { ticker: 'INVH', name: 'Invitation Homes Inc.', exchange: 'NYSE' },
  { ticker: 'IP', name: 'International Paper Company', exchange: 'NYSE' },
  { ticker: 'JBHT', name: 'J.B. Hunt Transport Services Inc.', exchange: 'NASDAQ' },
  { ticker: 'K', name: 'Kellanova', exchange: 'NYSE' },
  { ticker: 'LUV', name: 'Southwest Airlines Co.', exchange: 'NYSE' },
  { ticker: 'LKQ', name: 'LKQ Corporation', exchange: 'NASDAQ' },
  { ticker: 'L', name: 'Loews Corporation', exchange: 'NYSE' },
  { ticker: 'MAS', name: 'Masco Corporation', exchange: 'NYSE' },
  { ticker: 'MAA', name: 'Mid-America Apartment Communities Inc.', exchange: 'NYSE' },
  { ticker: 'MGM', name: 'MGM Resorts International', exchange: 'NYSE' },
  { ticker: 'MOS', name: 'The Mosaic Company', exchange: 'NYSE' },
  { ticker: 'NTAP', name: 'NetApp Inc.', exchange: 'NASDAQ' },
  { ticker: 'NVR', name: 'NVR Inc.', exchange: 'NYSE' },
  { ticker: 'NI', name: 'NiSource Inc.', exchange: 'NYSE' },
  { ticker: 'NRG', name: 'NRG Energy Inc.', exchange: 'NYSE' },
  { ticker: 'PNR', name: 'Pentair plc', exchange: 'NYSE' },
  { ticker: 'PKG', name: 'Packaging Corporation of America', exchange: 'NYSE' },
  { ticker: 'PFG', name: 'Principal Financial Group Inc.', exchange: 'NASDAQ' },
  { ticker: 'PNW', name: 'Pinnacle West Capital Corporation', exchange: 'NYSE' },
  { ticker: 'POOL', name: 'Pool Corporation', exchange: 'NASDAQ' },
  { ticker: 'PAYC', name: 'Paycom Software Inc.', exchange: 'NYSE' },
  { ticker: 'PHM', name: 'PulteGroup Inc.', exchange: 'NYSE' },
  { ticker: 'RF', name: 'Regions Financial Corporation', exchange: 'NYSE' },
  { ticker: 'RVTY', name: 'Revvity Inc.', exchange: 'NYSE' },
  { ticker: 'STE', name: 'STERIS plc', exchange: 'NYSE' },
  { ticker: 'STLD', name: 'Steel Dynamics Inc.', exchange: 'NASDAQ' },
  { ticker: 'STT', name: 'State Street Corporation', exchange: 'NYSE' },
  { ticker: 'SWK', name: 'Stanley Black & Decker Inc.', exchange: 'NYSE' },
  { ticker: 'SWKS', name: 'Skyworks Solutions Inc.', exchange: 'NASDAQ' },
  { ticker: 'TDY', name: 'Teledyne Technologies Inc.', exchange: 'NYSE' },
  { ticker: 'TER', name: 'Teradyne Inc.', exchange: 'NASDAQ' },
  { ticker: 'TPR', name: 'Tapestry Inc.', exchange: 'NYSE' },
  { ticker: 'TROW', name: 'T. Rowe Price Group Inc.', exchange: 'NASDAQ' },
  { ticker: 'TXT', name: 'Textron Inc.', exchange: 'NYSE' },
  { ticker: 'UAL', name: 'United Airlines Holdings Inc.', exchange: 'NASDAQ' },
  { ticker: 'UDR', name: 'UDR Inc.', exchange: 'NYSE' },
  { ticker: 'UHS', name: 'Universal Health Services Inc.', exchange: 'NYSE' },
  { ticker: 'VRSN', name: 'VeriSign Inc.', exchange: 'NASDAQ' },
  { ticker: 'VTRS', name: 'Viatris Inc.', exchange: 'NASDAQ' },
  { ticker: 'WRB', name: 'W. R. Berkley Corporation', exchange: 'NYSE' },
  { ticker: 'WAT', name: 'Waters Corporation', exchange: 'NYSE' },
  { ticker: 'WY', name: 'Weyerhaeuser Company', exchange: 'NYSE' },
  { ticker: 'WYNN', name: 'Wynn Resorts Limited', exchange: 'NASDAQ' },
  { ticker: 'XYL', name: 'Xylem Inc.', exchange: 'NYSE' },
  { ticker: 'ZBRA', name: 'Zebra Technologies Corporation', exchange: 'NASDAQ' },
  // Additional 100+ to reach near 500
  { ticker: 'AEE', name: 'Ameren Corporation', exchange: 'NYSE' },
  { ticker: 'AES', name: 'The AES Corporation', exchange: 'NYSE' },
  { ticker: 'AIZ', name: 'Assurant Inc.', exchange: 'NYSE' },
  { ticker: 'AKAM', name: 'Akamai Technologies Inc.', exchange: 'NASDAQ' },
  { ticker: 'ALK', name: 'Alaska Air Group Inc.', exchange: 'NYSE' },
  { ticker: 'AOS', name: 'A. O. Smith Corporation', exchange: 'NYSE' },
  { ticker: 'APA', name: 'APA Corporation', exchange: 'NASDAQ' },
  { ticker: 'APTV', name: 'Aptiv PLC', exchange: 'NYSE' },
  { ticker: 'ATVI', name: 'Activision Blizzard Inc.', exchange: 'NASDAQ' },
  { ticker: 'AWK', name: 'American Water Works Company Inc.', exchange: 'NYSE' },
  { ticker: 'BAX', name: 'Baxter International Inc.', exchange: 'NYSE' },
  { ticker: 'BEN', name: 'Franklin Resources Inc.', exchange: 'NYSE' },
  { ticker: 'BF.B', name: 'Brown-Forman Corporation Class B', exchange: 'NYSE' },
  { ticker: 'BIIB', name: 'Biogen Inc.', exchange: 'NASDAQ' },
  { ticker: 'BIO', name: 'Bio-Rad Laboratories Inc.', exchange: 'NYSE' },
  { ticker: 'BWA', name: 'BorgWarner Inc.', exchange: 'NYSE' },
  { ticker: 'BXP', name: 'Boston Properties Inc.', exchange: 'NYSE' },
  { ticker: 'CCL', name: 'Carnival Corporation', exchange: 'NYSE' },
  { ticker: 'CDAY', name: 'Ceridian HCM Holding Inc.', exchange: 'NYSE' },
  { ticker: 'CDNS', name: 'Cadence Design Systems Inc.', exchange: 'NASDAQ' },
  { ticker: 'CDW', name: 'CDW Corporation', exchange: 'NASDAQ' },
  { ticker: 'CF', name: 'CF Industries Holdings Inc.', exchange: 'NYSE' },
  { ticker: 'CHRW', name: 'C.H. Robinson Worldwide Inc.', exchange: 'NASDAQ' },
  { ticker: 'CINF', name: 'Cincinnati Financial Corporation', exchange: 'NASDAQ' },
  { ticker: 'CLX', name: 'The Clorox Company', exchange: 'NYSE' },
  { ticker: 'CMS', name: 'CMS Energy Corporation', exchange: 'NYSE' },
  { ticker: 'CPB', name: 'Campbell Soup Company', exchange: 'NYSE' },
  { ticker: 'CPT', name: 'Camden Property Trust', exchange: 'NYSE' },
  { ticker: 'CRL', name: 'Charles River Laboratories International Inc.', exchange: 'NYSE' },
  { ticker: 'CSCO', name: 'Cisco Systems Inc.', exchange: 'NASDAQ' },
  { ticker: 'CZR', name: 'Caesars Entertainment Inc.', exchange: 'NASDAQ' },
  { ticker: 'DG', name: 'Dollar General Corporation', exchange: 'NYSE' },
  { ticker: 'DGX', name: 'Quest Diagnostics Inc.', exchange: 'NYSE' },
  { ticker: 'DISH', name: 'DISH Network Corporation', exchange: 'NASDAQ' },
  { ticker: 'DPZ', name: 'Domino\'s Pizza Inc.', exchange: 'NYSE' },
  { ticker: 'DTE', name: 'DTE Energy Company', exchange: 'NYSE' },
  { ticker: 'DVA', name: 'DaVita Inc.', exchange: 'NYSE' },
  { ticker: 'ENPH', name: 'Enphase Energy Inc.', exchange: 'NASDAQ' },
  { ticker: 'EPAM', name: 'EPAM Systems Inc.', exchange: 'NYSE' },
  { ticker: 'EVRG', name: 'Evergy Inc.', exchange: 'NYSE' },
  { ticker: 'EXPE', name: 'Expedia Group Inc.', exchange: 'NASDAQ' },
  { ticker: 'FFIV', name: 'F5 Inc.', exchange: 'NASDAQ' },
  { ticker: 'FIS', name: 'Fidelity National Information Services Inc.', exchange: 'NYSE' },
  { ticker: 'FLT', name: 'FLEETCOR Technologies Inc.', exchange: 'NYSE' },
  { ticker: 'FMC', name: 'FMC Corporation', exchange: 'NYSE' },
  { ticker: 'FOX', name: 'Fox Corporation Class B', exchange: 'NASDAQ' },
  { ticker: 'FOXA', name: 'Fox Corporation Class A', exchange: 'NASDAQ' },
  { ticker: 'FRC', name: 'First Republic Bank', exchange: 'NYSE' },
  { ticker: 'FTV', name: 'Fortive Corporation', exchange: 'NYSE' },
  { ticker: 'GEN', name: 'Gen Digital Inc.', exchange: 'NASDAQ' },
  { ticker: 'GNRC', name: 'Generac Holdings Inc.', exchange: 'NYSE' },
  { ticker: 'GPC', name: 'Genuine Parts Company', exchange: 'NYSE' },
  { ticker: 'HAS', name: 'Hasbro Inc.', exchange: 'NASDAQ' },
  { ticker: 'HSIC', name: 'Henry Schein Inc.', exchange: 'NASDAQ' },
  { ticker: 'HST', name: 'Host Hotels & Resorts Inc.', exchange: 'NASDAQ' },
  { ticker: 'HWM', name: 'Howmet Aerospace Inc.', exchange: 'NYSE' },
  { ticker: 'IEX', name: 'IDEX Corporation', exchange: 'NYSE' },
  { ticker: 'ILMN', name: 'Illumina Inc.', exchange: 'NASDAQ' },
  { ticker: 'INCY', name: 'Incyte Corporation', exchange: 'NASDAQ' },
  { ticker: 'IPG', name: 'The Interpublic Group of Companies Inc.', exchange: 'NYSE' },
  { ticker: 'IRM', name: 'Iron Mountain Inc.', exchange: 'NYSE' },
  { ticker: 'JKHY', name: 'Jack Henry & Associates Inc.', exchange: 'NASDAQ' },
  { ticker: 'JNPR', name: 'Juniper Networks Inc.', exchange: 'NYSE' },
  { ticker: 'KDP', name: 'Keurig Dr Pepper Inc.', exchange: 'NASDAQ' },
  { ticker: 'KIM', name: 'Kimco Realty Corporation', exchange: 'NYSE' },
  { ticker: 'LH', name: 'Laboratory Corporation of America Holdings', exchange: 'NYSE' },
  { ticker: 'LNT', name: 'Alliant Energy Corporation', exchange: 'NASDAQ' },
  { ticker: 'LW', name: 'Lamb Weston Holdings Inc.', exchange: 'NYSE' },
  { ticker: 'LYV', name: 'Live Nation Entertainment Inc.', exchange: 'NYSE' },
  { ticker: 'MMM', name: '3M Company', exchange: 'NYSE' },
  { ticker: 'MKTX', name: 'MarketAxess Holdings Inc.', exchange: 'NASDAQ' },
  { ticker: 'MSCI', name: 'MSCI Inc.', exchange: 'NYSE' },
  { ticker: 'MTN', name: 'Vail Resorts Inc.', exchange: 'NYSE' },
  { ticker: 'NCLH', name: 'Norwegian Cruise Line Holdings Ltd.', exchange: 'NYSE' },
  { ticker: 'NDSN', name: 'Nordson Corporation', exchange: 'NASDAQ' },
  { ticker: 'NWL', name: 'Newell Brands Inc.', exchange: 'NASDAQ' },
  { ticker: 'NWS', name: 'News Corporation Class B', exchange: 'NASDAQ' },
  { ticker: 'NWSA', name: 'News Corporation Class A', exchange: 'NASDAQ' },
  { ticker: 'OMC', name: 'Omnicom Group Inc.', exchange: 'NYSE' },
  { ticker: 'PEAK', name: 'Healthpeak Properties Inc.', exchange: 'NYSE' },
  { ticker: 'PEN', name: 'Penumbra Inc.', exchange: 'NYSE' },
  { ticker: 'PKI', name: 'PerkinElmer Inc.', exchange: 'NYSE' },
  { ticker: 'PTC', name: 'PTC Inc.', exchange: 'NASDAQ' },
  { ticker: 'QRVO', name: 'Qorvo Inc.', exchange: 'NASDAQ' },
  { ticker: 'RE', name: 'Everest Re Group Ltd.', exchange: 'NYSE' },
  { ticker: 'REG', name: 'Regency Centers Corporation', exchange: 'NASDAQ' },
  { ticker: 'ROL', name: 'Rollins Inc.', exchange: 'NYSE' },
  { ticker: 'SEDG', name: 'SolarEdge Technologies Inc.', exchange: 'NASDAQ' },
  { ticker: 'SEE', name: 'Sealed Air Corporation', exchange: 'NYSE' },
  { ticker: 'SJM', name: 'The J. M. Smucker Company', exchange: 'NYSE' },
  { ticker: 'SNA', name: 'Snap-on Inc.', exchange: 'NYSE' },
  { ticker: 'TDG', name: 'TransDigm Group Inc.', exchange: 'NYSE' },
  { ticker: 'TECH', name: 'Bio-Techne Corporation', exchange: 'NASDAQ' },
  { ticker: 'TRMB', name: 'Trimble Inc.', exchange: 'NASDAQ' },
  { ticker: 'TRU', name: 'TransUnion', exchange: 'NYSE' },
  { ticker: 'TSCO', name: 'Tractor Supply Company', exchange: 'NASDAQ' },
  { ticker: 'ULTA', name: 'Ulta Beauty Inc.', exchange: 'NASDAQ' },
  { ticker: 'UNM', name: 'Unum Group', exchange: 'NYSE' },
  { ticker: 'VFC', name: 'V.F. Corporation', exchange: 'NYSE' },
  { ticker: 'VNO', name: 'Vornado Realty Trust', exchange: 'NYSE' },
  { ticker: 'WBA', name: 'Walgreens Boots Alliance Inc.', exchange: 'NASDAQ' },
  { ticker: 'WDC', name: 'Western Digital Corporation', exchange: 'NASDAQ' },
  { ticker: 'WHR', name: 'Whirlpool Corporation', exchange: 'NYSE' },
  { ticker: 'WU', name: 'The Western Union Company', exchange: 'NYSE' },
  { ticker: 'WLTW', name: 'Willis Towers Watson Public Limited Company', exchange: 'NASDAQ' },
  { ticker: 'ZION', name: 'Zions Bancorporation N.A.', exchange: 'NASDAQ' },
  // ETFs
  { ticker: 'SPY', name: 'SPDR S&P 500 ETF Trust', exchange: 'NYSE' },
  { ticker: 'QQQ', name: 'Invesco QQQ Trust', exchange: 'NASDAQ' },
  { ticker: 'IWM', name: 'iShares Russell 2000 ETF', exchange: 'NYSE' },
  { ticker: 'DIA', name: 'SPDR Dow Jones Industrial Average ETF', exchange: 'NYSE' },
  { ticker: 'VTI', name: 'Vanguard Total Stock Market ETF', exchange: 'NYSE' },
  { ticker: 'VOO', name: 'Vanguard S&P 500 ETF', exchange: 'NYSE' },
  { ticker: 'VEA', name: 'Vanguard FTSE Developed Markets ETF', exchange: 'NYSE' },
  { ticker: 'VWO', name: 'Vanguard FTSE Emerging Markets ETF', exchange: 'NYSE' },
  { ticker: 'AGG', name: 'iShares Core U.S. Aggregate Bond ETF', exchange: 'NYSE' },
  { ticker: 'XLK', name: 'Technology Select Sector SPDR Fund', exchange: 'NYSE' },
  { ticker: 'XLF', name: 'Financial Select Sector SPDR Fund', exchange: 'NYSE' },
  { ticker: 'XLE', name: 'Energy Select Sector SPDR Fund', exchange: 'NYSE' },
  { ticker: 'XLV', name: 'Health Care Select Sector SPDR Fund', exchange: 'NYSE' },
  { ticker: 'XLI', name: 'Industrial Select Sector SPDR Fund', exchange: 'NYSE' },
  { ticker: 'XLY', name: 'Consumer Discretionary Select Sector SPDR Fund', exchange: 'NYSE' },
  { ticker: 'XLP', name: 'Consumer Staples Select Sector SPDR Fund', exchange: 'NYSE' },
  { ticker: 'XLRE', name: 'Real Estate Select Sector SPDR Fund', exchange: 'NYSE' },
  { ticker: 'XLC', name: 'Communication Services Select Sector SPDR Fund', exchange: 'NYSE' },
  { ticker: 'XLU', name: 'Utilities Select Sector SPDR Fund', exchange: 'NYSE' },
  { ticker: 'XLB', name: 'Materials Select Sector SPDR Fund', exchange: 'NYSE' },
];
