-- Fix cron job schedules (pg_cron doesn't support seconds)
-- Delete incorrect jobs
SELECT cron.unschedule(jobname) 
FROM cron.job 
WHERE jobname LIKE 'prices-batch-%';

-- Create 52 batch jobs that all run simultaneously every minute
-- Each processes a different slice of 20 assets
SELECT cron.schedule('prices-batch-00', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 0}'::jsonb) $$);
SELECT cron.schedule('prices-batch-01', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 1}'::jsonb) $$);
SELECT cron.schedule('prices-batch-02', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 2}'::jsonb) $$);
SELECT cron.schedule('prices-batch-03', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 3}'::jsonb) $$);
SELECT cron.schedule('prices-batch-04', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 4}'::jsonb) $$);
SELECT cron.schedule('prices-batch-05', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 5}'::jsonb) $$);
SELECT cron.schedule('prices-batch-06', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 6}'::jsonb) $$);
SELECT cron.schedule('prices-batch-07', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 7}'::jsonb) $$);
SELECT cron.schedule('prices-batch-08', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 8}'::jsonb) $$);
SELECT cron.schedule('prices-batch-09', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 9}'::jsonb) $$);
SELECT cron.schedule('prices-batch-10', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 10}'::jsonb) $$);
SELECT cron.schedule('prices-batch-11', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 11}'::jsonb) $$);
SELECT cron.schedule('prices-batch-12', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 12}'::jsonb) $$);
SELECT cron.schedule('prices-batch-13', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 13}'::jsonb) $$);
SELECT cron.schedule('prices-batch-14', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 14}'::jsonb) $$);
SELECT cron.schedule('prices-batch-15', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 15}'::jsonb) $$);
SELECT cron.schedule('prices-batch-16', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 16}'::jsonb) $$);
SELECT cron.schedule('prices-batch-17', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 17}'::jsonb) $$);
SELECT cron.schedule('prices-batch-18', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 18}'::jsonb) $$);
SELECT cron.schedule('prices-batch-19', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 19}'::jsonb) $$);
SELECT cron.schedule('prices-batch-20', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 20}'::jsonb) $$);
SELECT cron.schedule('prices-batch-21', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 21}'::jsonb) $$);
SELECT cron.schedule('prices-batch-22', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 22}'::jsonb) $$);
SELECT cron.schedule('prices-batch-23', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 23}'::jsonb) $$);
SELECT cron.schedule('prices-batch-24', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 24}'::jsonb) $$);
SELECT cron.schedule('prices-batch-25', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 25}'::jsonb) $$);
SELECT cron.schedule('prices-batch-26', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 26}'::jsonb) $$);
SELECT cron.schedule('prices-batch-27', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 27}'::jsonb) $$);
SELECT cron.schedule('prices-batch-28', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 28}'::jsonb) $$);
SELECT cron.schedule('prices-batch-29', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 29}'::jsonb) $$);
SELECT cron.schedule('prices-batch-30', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 30}'::jsonb) $$);
SELECT cron.schedule('prices-batch-31', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 31}'::jsonb) $$);
SELECT cron.schedule('prices-batch-32', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 32}'::jsonb) $$);
SELECT cron.schedule('prices-batch-33', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 33}'::jsonb) $$);
SELECT cron.schedule('prices-batch-34', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 34}'::jsonb) $$);
SELECT cron.schedule('prices-batch-35', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 35}'::jsonb) $$);
SELECT cron.schedule('prices-batch-36', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 36}'::jsonb) $$);
SELECT cron.schedule('prices-batch-37', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 37}'::jsonb) $$);
SELECT cron.schedule('prices-batch-38', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldWVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 38}'::jsonb) $$);
SELECT cron.schedule('prices-batch-39', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 39}'::jsonb) $$);
SELECT cron.schedule('prices-batch-40', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 40}'::jsonb) $$);
SELECT cron.schedule('prices-batch-41', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 41}'::jsonb) $$);
SELECT cron.schedule('prices-batch-42', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 42}'::jsonb) $$);
SELECT cron.schedule('prices-batch-43', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 43}'::jsonb) $$);
SELECT cron.schedule('prices-batch-44', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 44}'::jsonb) $$);
SELECT cron.schedule('prices-batch-45', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 45}'::jsonb) $$);
SELECT cron.schedule('prices-batch-46', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 46}'::jsonb) $$);
SELECT cron.schedule('prices-batch-47', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 47}'::jsonb) $$);
SELECT cron.schedule('prices-batch-48', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 48}'::jsonb) $$);
SELECT cron.schedule('prices-batch-49', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 49}'::jsonb) $$);
SELECT cron.schedule('prices-batch-50', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 50}'::jsonb) $$);
SELECT cron.schedule('prices-batch-51', '* * * * *', $$ SELECT net.http_post(url := 'https://detxhoqiarohjevedmxh.supabase.co/functions/v1/ingest-prices-yahoo', headers := '{"Content-Type": "application/json", "Authorization": "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRldHhob3FpYXJvaGpldmVkbXhoIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2MDYwMjE0NiwiZXhwIjoyMDc2MTc4MTQ2fQ.vXy9OmULGwrb7lKLuCxCx6HpT2M-lNpK97pn63Y-E8Q"}'::jsonb, body := '{"batch_id": 51}'::jsonb) $$);